import { SEAWATER_DENSITY, STANDARD_GRAVITY, TNT_SPECIFIC_ENERGY } from '../../constants.js';
import { synolakisRunup } from '../tsunami/extendedEffects.js';
import type { Joules, Meters, MetersPerSecond, Seconds } from '../../units.js';
import { J, m } from '../../units.js';
import {
  impactAmplitudeAtDistance,
  impactCavityRadius,
  impactSourceAmplitude,
} from '../tsunami/impact.js';
import { shallowWaterWaveSpeed, tsunamiTravelTime } from '../tsunami/propagation.js';

/**
 * Underwater / contact-water nuclear explosion → tsunami source.
 *
 * The Ward & Asphaug (2000) cavity-radius formula is energy-based and
 * works for any energy source that couples mechanically to a water
 * column. For a nuclear or chemical explosion only a fraction of the
 * total yield ends up as bulk water displacement — the rest goes into
 * compression heating, gas-bubble pulsation, and acoustic radiation.
 * Le Méhauté & Wang (1996) and Glasstone & Dolan (1977) §6 quote
 * mechanical-coupling efficiencies in the 5–15 % range for shallow
 * underwater bursts, peaking near a "scaled depth" z/W^(1/3) ≈ 4 m/kt^(1/3).
 *
 * For the popular-science envelope we use a single canonical
 * coupling fraction of 0.08, which reproduces the Glasstone Table 6.50
 * ≈ 180 m source amplitude for a 1 Mt optimum-depth burst within a
 * factor of two. Outside that regime (very shallow contact bursts on
 * water, or extremely deep submarine bursts) the wave is overestimated
 * — we accept the bias rather than introduce a depth-dependent fit
 * that would still need ±50 % scatter bands to honour the published
 * uncertainty.
 *
 * References:
 *   Glasstone, S. & Dolan, P. J. (1977). "The Effects of Nuclear
 *     Weapons" (3rd ed.), §6.40–§6.65 (Underwater bursts), Table 6.50.
 *   Le Méhauté, B. & Wang, S. (1996). "Water Waves Generated by
 *     Underwater Explosion." Advanced Series on Ocean Engineering 10.
 *     World Scientific. ISBN 978-981-02-2083-3.
 *   Ward, S. N. & Asphaug, E. (2000). "Asteroid Impact Tsunami:
 *     A Probabilistic Hazard Assessment." Icarus 145(1), Eq. 3
 *     (re-used here with a coupling correction).
 */

/** Mechanical coupling fraction at the optimum depth. Tuned so that
 *  1 Mt at that depth reproduces Glasstone Table 6.50's ≈ 180 m
 *  source amplitude; the sources put the shallow-underwater range at
 *  5–15 %, and this is the middle of it. */
export const EXPLOSION_WATER_COUPLING = 0.08;

/** Scaled depth at which wave-making peaks, in metres per cube root
 *  of a kilotonne. Glasstone & Dolan §6.40; the figure this module
 *  has cited since it was written. */
export const OPTIMUM_SCALED_DEPTH = 4;

/**
 * Width of the efficiency curve in log-space around that optimum.
 *
 * This is the project's own composition and the one number here with
 * no page behind it. The shape is not arbitrary — an efficiency with
 * a single optimum and a fall-off on both sides is log-normal in the
 * scaled depth, and both fall-offs have a mechanism — but the width
 * is chosen, and it is chosen so the curve spans the "shallow
 * underwater" band the sources describe rather than collapsing onto
 * a single depth. Expect the ±50 % scatter this file predicted when
 * it declined to fit the curve at all.
 */
export const COUPLING_LOG_WIDTH = 0.6;

/**
 * How much of a burst's energy goes into making waves, as a fraction
 * of what an optimally placed one would manage.
 *
 * `scaledDepth` is z/W^(1/3) in m·kt^(−1/3), positive downward. The
 * curve is a log-normal peaked at {@link OPTIMUM_SCALED_DEPTH}, and
 * each side of the peak has its own reason:
 *
 *   Too shallow — the gas globe reaches the surface before it has
 *   finished pushing, opens to the atmosphere, and the energy that
 *   would have lifted water leaves as air shock and spray. At the
 *   surface itself there is nothing left to lift with, which is the
 *   same reason this module has always given an airburst nothing:
 *   the venting is total either way, and the curve simply arrives at
 *   that answer continuously instead of by a gate.
 *
 *   Too deep — the bubble oscillates and decays without ever
 *   breaking through, and the surface barely knows it happened.
 *
 * The record agrees with the shape at the one place it is loud: the
 * famous explosion-generated wave, Crossroads Baker in 1946, came
 * from a charge suspended twenty-seven metres down, while the surface
 * bursts of the same era — Bravo on its reef, Mike on its islet —
 * are remembered for their fireballs and their craters and not for
 * any wave at all.
 */
export function waveCouplingEfficiency(scaledDepth: number): number {
  if (!Number.isFinite(scaledDepth) || scaledDepth <= 0) return 0;
  const ratio = scaledDepth / OPTIMUM_SCALED_DEPTH;
  const exponent = Math.log(ratio) ** 2 / (2 * COUPLING_LOG_WIDTH * COUPLING_LOG_WIDTH);
  const efficiency = Math.exp(-exponent);
  return Number.isFinite(efficiency) ? Math.min(1, Math.max(0, efficiency)) : 0;
}

export interface ExplosionTsunamiInput {
  /** Total explosion yield (J). */
  yieldEnergy: Joules;
  /** Depth of the burst point below the water surface (m), positive
   *  downward. Zero for a burst sitting on the surface and negative
   *  for one in the air; both couple next to nothing, and the curve
   *  in {@link waveCouplingEfficiency} says so continuously rather
   *  than by a threshold. Omitted means the optimum depth, which is
   *  what this module assumed before the curve existed. */
  burstDepth?: Meters;
  /** Water depth at the burst site (m). Must be > 0 for a wave to
   *  form; the caller decides the threshold. */
  waterDepth: Meters;
  /** Mean basin depth used for the shallow-water travel-time
   *  calculation (m). Defaults to the global ocean mean of 4 km. */
  meanOceanDepth?: Meters;
  /** Beach slope (rad) for the Synolakis run-up. Defaults to
   *  `atan(1/100)` when omitted; the caller (typically the store)
   *  should pass a DEM-driven value when the click point is on a
   *  real coastal slope. */
  coastalBeachSlopeRad?: number;
}

export interface ExplosionTsunamiResult {
  /** Equivalent Ward-Asphaug cavity radius after the coupling
   *  correction (m). */
  cavityRadius: Meters;
  /** Initial wave amplitude at the cavity rim (m). */
  sourceAmplitude: Meters;
  /** Far-field amplitude at 100 km from the burst (m). */
  amplitudeAt100km: Meters;
  /** Far-field amplitude at 1 000 km from the burst (m). */
  amplitudeAt1000km: Meters;
  /** Travel time from the burst to the 100 km contour (s). */
  travelTimeTo100km: Seconds;
  /** Travel time from the burst to the 1 000 km contour (s). */
  travelTimeTo1000km: Seconds;
  /** Coupling fraction applied — echoed for the report tooltip. */
  couplingFraction: number;
  /** Echo of the basin depth used for travel-time. */
  meanOceanDepth: Meters;
  /** Open-ocean phase speed `c = √(g·h)` of a long gravity wave on
   *  the basin (Lamb 1932 §170). At the default 4 km mean depth
   *  this is ≈ 198 m/s ≈ 713 km/h. */
  deepWaterCelerity: MetersPerSecond;
  /** Source-radiated wavelength (m). For an explosion-driven cavity
   *  collapse the dominant wavelength is set by the cavity diameter
   *  (≈ 2 × R_C), the same scaling that holds for impact-driven
   *  cavities under the Ward & Asphaug 2000 framework. */
  sourceWavelength: Meters;
  /** Dominant wave period at the source (s). T = λ / c. */
  dominantPeriod: Seconds;
  /** Synolakis (1987) run-up on a 1:100 plane beach with 10 m
   *  offshore depth, using the 100 km amplitude as the incident
   *  wave. Illustrative coastal-inundation estimate. */
  runupAt100km: Meters;
  /** Estimated inland inundation distance at the 100 km contour
   *  (m). Geometric `runup × cot(slope)` envelope on a 1:100
   *  reference beach (FEMA 55 §3.4). */
  inundationDistanceAt100km: Meters;
  /** Beach slope (rad) actually consumed by the Synolakis run-up. */
  beachSlopeRadUsed: number;
  /** True when {@link beachSlopeRadUsed} came from a DEM sample at
   *  the click site (rather than the 1:100 reference fallback). */
  beachSlopeFromDEM: boolean;
}

/**
 * Compute the explosion-driven tsunami source from a yield and water
 * depth. Returns null when the inputs cannot drive a wave (zero or
 * negative yield, zero water depth).
 */
export function explosionTsunami(input: ExplosionTsunamiInput): ExplosionTsunamiResult | null {
  const yieldJ = input.yieldEnergy as number;
  const depth = input.waterDepth as number;
  if (!Number.isFinite(yieldJ) || yieldJ <= 0) return null;
  if (!Number.isFinite(depth) || depth <= 0) return null;

  const meanOceanDepth = input.meanOceanDepth ?? m(4_000);
  // How well this burst is placed for making waves. A charge hung at
  // the optimum depth couples the full eight per cent; one resting on
  // the surface vents almost all of it to the air.
  const kilotons = yieldJ / (TNT_SPECIFIC_ENERGY * 1e6);
  const scaledDepth =
    input.burstDepth === undefined
      ? OPTIMUM_SCALED_DEPTH
      : (input.burstDepth as number) / Math.max(Math.cbrt(kilotons), 1e-9);
  const efficiency = waveCouplingEfficiency(scaledDepth);
  if (efficiency <= 0) return null;
  const effectiveEnergy = J(yieldJ * EXPLOSION_WATER_COUPLING * efficiency);
  const cavityRadius = impactCavityRadius({
    kineticEnergy: effectiveEnergy,
    waterDensity: SEAWATER_DENSITY,
    surfaceGravity: STANDARD_GRAVITY,
  });
  const sourceAmplitude = impactSourceAmplitude(cavityRadius);
  const amp100 = impactAmplitudeAtDistance({
    sourceAmplitude,
    cavityRadius,
    distance: m(100_000),
  });
  const amp1000 = impactAmplitudeAtDistance({
    sourceAmplitude,
    cavityRadius,
    distance: m(1_000_000),
  });

  const celerity = shallowWaterWaveSpeed(meanOceanDepth);
  const wavelength = m(2 * (cavityRadius as number));
  const period = (wavelength / Math.max(celerity, 1e-6)) as Seconds;
  // Use the 100 km contour as the runup anchor for explosions —
  // amplitudes drop off faster than for impacts (smaller cavities),
  // so the 100 km headline is more pedagogically useful than a
  // 1 000 km figure that is often sub-cm. Beach slope: caller-
  // supplied DEM value when in the [1:1000, 1:3] envelope, else
  // 1:100 reference.
  const FALLBACK_SLOPE_RAD = Math.atan(1 / 100);
  const SLOPE_LOWER = Math.atan(1 / 1000);
  const SLOPE_UPPER = Math.atan(1 / 3);
  const supplied = input.coastalBeachSlopeRad;
  const slopeFromDEM =
    supplied !== undefined &&
    Number.isFinite(supplied) &&
    supplied >= SLOPE_LOWER &&
    supplied <= SLOPE_UPPER;
  const beachSlopeRad = slopeFromDEM ? supplied : FALLBACK_SLOPE_RAD;
  const runup100 = synolakisRunup(amp100, beachSlopeRad, m(10));
  const inundation100 = m((runup100 as number) / Math.tan(beachSlopeRad));

  return {
    cavityRadius,
    sourceAmplitude,
    amplitudeAt100km: amp100,
    amplitudeAt1000km: amp1000,
    travelTimeTo100km: tsunamiTravelTime(m(100_000), meanOceanDepth),
    travelTimeTo1000km: tsunamiTravelTime(m(1_000_000), meanOceanDepth),
    couplingFraction: EXPLOSION_WATER_COUPLING,
    meanOceanDepth,
    deepWaterCelerity: celerity,
    sourceWavelength: wavelength,
    dominantPeriod: period,
    runupAt100km: runup100,
    inundationDistanceAt100km: inundation100,
    beachSlopeRadUsed: beachSlopeRad,
    beachSlopeFromDEM: slopeFromDEM,
  };
}
