// Generated by scripts/benchmark/burn-curves.py from the public scan of
// Glasstone, S. & Dolan, P. J. (1977), The Effects of Nuclear Weapons, 3rd
// edition (DTIC ADA087568), page 564, Figure 12.64. Do not edit by hand:
// rule 80 of burnRules.ts says what these are and how they were read.

/** The yields (kt) the curves are read at. */
export const BURN_CURVE_YIELDS_KT: readonly number[] = [1, 3, 10, 30, 100, 300, 1000, 3000, 10000];

/** The radiant exposure (cal/cm²) required to produce a burn of that degree
 *  on that skin pigmentation, at each of {@link BURN_CURVE_YIELDS_KT}. The
 *  figure attaches no probability to a curve; its neighbour 12.65 does, and is
 *  not this one. Traced from the scan; the reading is
 *  good to about a tenth of a cal/cm², half the thickness of a printed
 *  curve. */
// prettier-ignore
export const BURN_CURVES: readonly (readonly [string, string, readonly number[]])[] = [
  ['third', 'light', [6.82, 7.11, 7.64, 8.36, 9.20, 9.98, 10.87, 11.72, 12.61]],
  ['third', 'medium', [6.21, 6.48, 6.97, 7.59, 8.39, 9.16, 10.04, 10.87, 11.75]],
  ['third', 'dark', [5.62, 5.88, 6.29, 6.76, 7.37, 8.02, 8.80, 9.54, 10.36]],
  ['second', 'light', [4.43, 4.55, 4.83, 5.17, 5.66, 6.17, 6.82, 7.46, 8.19]],
  ['second', 'medium', [4.04, 4.14, 4.37, 4.70, 5.17, 5.68, 6.30, 6.93, 7.62]],
  ['second', 'dark', [3.60, 3.70, 3.91, 4.20, 4.59, 5.02, 5.56, 6.10, 6.57]],
  ['first', 'light', [2.28, 2.45, 2.65, 2.83, 3.07, 3.29, 3.57, 3.94, 4.46]],
  ['first', 'medium', [2.08, 2.24, 2.43, 2.60, 2.81, 3.04, 3.32, 3.65, 4.16]],
  ['first', 'dark', [1.86, 1.99, 2.15, 2.29, 2.47, 2.65, 2.90, 3.22, 3.69]],
];

/** The span of yields the trace actually covered, curve by curve (kt). */
// prettier-ignore
export const BURN_CURVE_SPAN_KT: readonly (readonly [number, number])[] = [
  [1.04, 9129],
  [1.04, 9323],
  [1.04, 9521],
  [1.04, 9521],
  [1.04, 9521],
  [1.04, 7716],
  [1.04, 9521],
  [1.04, 9521],
  [1.04, 9521],
];
