// Generated by scripts/benchmark/burn-probability-curves.py from the public
// scan of Glasstone, S. & Dolan, P. J. (1977), The Effects of Nuclear Weapons,
// 3rd edition (DTIC ADA087568), page 565, Figure 12.65. Do not edit by hand:
// rule 114 of validation/burnProbabilityRules.ts says what these are and how
// they were read.

/** The yields (kt) the curves are read at. */
export const BURN_PROBABILITY_YIELDS_KT: readonly number[] = [
  1, 3, 10, 30, 100, 300, 1000, 3000, 10000,
];

/**
 * The radiant exposure (cal/cm²) at which a share of an average unshielded
 * population taking no evasive action has a burn of that degree, at each of
 * {@link BURN_PROBABILITY_YIELDS_KT}: the 18 % line, the 50 % line, and the
 * upper line, which is 82 % for the first and second degrees and 100 % for the
 * third — the figure draws no 82 % third-degree curve. Traced from the scan;
 * the reading is good to about a tenth of a cal/cm², half the thickness of a
 * printed curve.
 */
// prettier-ignore
export const BURN_PROBABILITY_CURVES: readonly (readonly [string, number, readonly number[], readonly number[], readonly number[]])[] = [
  ['first', 0.82, [1.11, 1.24, 1.39, 1.52, 1.65, 1.78, 1.93, 2.07, 2.19], [1.92, 2.11, 2.33, 2.54, 2.79, 2.97, 3.20, 3.41, 3.64], [2.87, 3.16, 3.48, 3.77, 4.10, 4.39, 4.71, 5.01, 5.32]],
  ['second', 0.82, [2.87, 3.16, 3.48, 3.77, 4.10, 4.39, 4.71, 5.01, 5.32], [3.97, 4.33, 4.72, 5.09, 5.48, 5.84, 6.25, 6.60, 7.00], [4.99, 5.40, 5.87, 6.30, 6.76, 7.19, 7.65, 8.09, 8.56]],
  ['third', 1.00, [4.99, 5.40, 5.87, 6.30, 6.76, 7.19, 7.65, 8.09, 8.56], [5.97, 6.55, 7.22, 7.80, 8.46, 9.07, 9.72, 10.32, 10.98], [6.99, 7.67, 8.44, 9.14, 9.89, 10.60, 11.37, 12.05, 12.80]],
];

/** The book's own worked example (§12.65), as the trace reproduces it: at 1 Mt
 *  a population between these two exposures takes 18 % second-degree burns and
 *  the rest first-degree. The book reads the band as 4.5 to 6. */
export const BURN_PROBABILITY_WORKED_EXAMPLE_1MT: readonly [number, number] = [4.71, 6.25];
