import { writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { NCEI_EARTHQUAKE_ROWS } from '../src/physics/validation/heldOutByRuleData.js';
import { areasAbove, type Coverage } from './build-shakemap-fixtures.js';

/**
 * The ShakeMap footprints of the earthquakes held out by rule, for
 * rule 18 of `src/physics/validation/contourLaws.ts`.
 *
 * For every row of rule 11's set, the preferred ShakeMap of its USGS
 * ComCat event, read in memory from its low-resolution MMI coverage,
 * and the ground area at or above MMI VII, VIII and IX summed as
 * `pnpm shakemap:build` sums it. Only the areas are written. Nothing
 * here runs the simulator.
 *
 * Usage:
 *   pnpm exec tsx scripts/build-rule-shakemaps.ts
 *
 * ShakeMaps are revised, so a run on another day can write different
 * areas; the file in the repository is the one the rule was applied
 * to, and it records the day it was read.
 */

const COVERAGE = 'download/coverage_mmi_low_res.covjson';
const CONCURRENCY = 4;

async function json(url: string): Promise<unknown> {
  for (let attempt = 0; ; attempt++) {
    try {
      const res = await fetch(url, { headers: { 'User-Agent': 'nimbus-validation' } });
      if (!res.ok) throw new Error(`fetch ${url}: ${res.status.toString()}`);
      return await res.json();
    } catch (error) {
      if (attempt >= 4) throw error;
      await new Promise((r) => setTimeout(r, 2_000 * (attempt + 1)));
    }
  }
}

interface Detail {
  properties: {
    products: {
      shakemap?: {
        properties: { maxmmi?: string };
        contents: Record<string, { url: string } | undefined>;
      }[];
    };
  };
}

interface Row {
  comcat: string;
  maxMmi: number;
  areaKm2: Record<number, number>;
}

async function one(comcat: string): Promise<Row | null> {
  const detail = (await json(
    `https://earthquake.usgs.gov/fdsnws/event/1/query?eventid=${comcat}&format=geojson`
  )) as Detail;
  const shakemap = detail.properties.products.shakemap?.[0];
  const url = shakemap?.contents[COVERAGE]?.url;
  if (shakemap === undefined || url === undefined) return null;
  const coverage = (await json(url)) as Coverage;
  return {
    comcat,
    maxMmi: Number(shakemap.properties.maxmmi ?? 'NaN'),
    areaKm2: areasAbove(coverage),
  };
}

async function main(): Promise<void> {
  const ids = NCEI_EARTHQUAKE_ROWS.map((r) => r.comcat);
  const rows: Row[] = [];
  const missing: string[] = [];
  let next = 0;
  await Promise.all(
    Array.from({ length: CONCURRENCY }, async () => {
      while (next < ids.length) {
        const id = ids[next++];
        if (id === undefined) break;
        const row = await one(id);
        if (row === null) missing.push(id);
        else rows.push(row);
      }
    })
  );
  const order = new Map(ids.map((id, i) => [id, i]));
  rows.sort((a, b) => (order.get(a.comcat) ?? 0) - (order.get(b.comcat) ?? 0));
  missing.sort((a, b) => (order.get(a) ?? 0) - (order.get(b) ?? 0));
  const readOn = new Date().toISOString().slice(0, 10);
  const body = `// Generated by scripts/build-rule-shakemaps.ts on ${readOn}. Do not edit
// by hand: rule 18 of contourLaws.ts says what these are and how they
// were summed. USGS ShakeMap (${COVERAGE}), public domain.

import type { ShakemapAreas } from './contourLaws.js';

export const RULE_SHAKEMAPS_READ_ON = '${readOn}';

export const RULE_SHAKEMAPS: readonly ShakemapAreas[] = [
${rows
  .map(
    (r) =>
      `  { comcat: '${r.comcat}', maxMmi: ${Number.isFinite(r.maxMmi) ? r.maxMmi.toFixed(2) : 'Number.NaN'}, areaKm2: { 7: ${(r.areaKm2[7] ?? 0).toFixed(0)}, 8: ${(r.areaKm2[8] ?? 0).toFixed(0)}, 9: ${(r.areaKm2[9] ?? 0).toFixed(0)} } },`
  )
  .join('\n')}
];

/** Rows of rule 11's set whose ComCat event carries no ShakeMap with
 *  a low-resolution MMI coverage. */
export const RULE_SHAKEMAPS_MISSING: readonly string[] = [
${missing.map((id) => `  '${id}',`).join('\n')}
];
`;
  const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
  const out = join(root, 'src', 'physics', 'validation', 'ruleShakemapData.ts');
  writeFileSync(out, body);
  console.error(
    `wrote ${rows.length.toString()} ShakeMaps, ${missing.length.toString()} missing → ${out}`
  );
}

await main();
