import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * The reference values the intensity rings are verified against, taken
 * from the test data of the OpenQuake Engine (GEM Foundation,
 * AGPL-3.0-or-later, github.com/gem/oq-engine):
 *
 *   openquake/hazardlib/tests/gsim/data/BSSA2014/BSSA_2014_MEAN.csv
 *   openquake/hazardlib/tests/gsim/data/BSSA2014/BSSA_2014_NOSOF_MEAN.csv
 *   openquake/hazardlib/tests/gsim/data/BSSA2014/BSSA_2014_TOTAL_STD.csv
 *   openquake/hazardlib/tests/gsim/data/a12ipe/AWW_IPE_RHYPO_MEAN.csv
 *   openquake/hazardlib/tests/gsim/data/a12ipe/AWW_IPE_RHYPO_SIGMA.csv
 *
 * which OpenQuake's tests say were generated from David M. Boore's
 * Fortran implementation of Boore et al. 2014 (July 2014) and from an
 * independent Matlab implementation of Allen, Wald & Worden 2012. Only
 * the peak ground acceleration, peak ground velocity and intensity
 * columns are kept.
 *
 * Usage:
 *   pnpm exec tsx scripts/build-openquake-reference.ts <directory with the five files>
 */

const dir = process.argv[2] ?? '';
if (dir === '') throw new Error('usage: build-openquake-reference.ts <directory>');

function csv(name: string): Record<string, string>[] {
  const [head, ...lines] = readFileSync(join(dir, name), 'utf8').trim().split('\n');
  const cols = (head ?? '').split(',');
  return lines.map((line) => Object.fromEntries(line.split(',').map((v, i) => [cols[i] ?? '', v])));
}

const num = (value: string | undefined): number => {
  const n = Number(value);
  if (!Number.isFinite(n)) throw new Error(`not a number: ${String(value)}`);
  return n;
};

const bssaRows = csv('BSSA_2014_MEAN.csv').filter((r) => r.result_type === 'MEAN');
const nosofRows = csv('BSSA_2014_NOSOF_MEAN.csv').filter((r) => r.result_type === 'MEAN');
const stdRows = csv('BSSA_2014_TOTAL_STD.csv').filter((r) => r.result_type === 'TOTAL_STDDEV');
const withRake = (rows: Record<string, string>[], column: 'pga' | 'pgv'): number[][] =>
  rows.map((r) => [
    num(r.rup_mag),
    num(r.rup_rake),
    num(r.dist_rjb),
    num(r.site_vs30),
    num(r[column]),
  ]);
const bssa = withRake(bssaRows, 'pga');
const bssaPgv = withRake(bssaRows, 'pgv');
const nosof = nosofRows.map((r) => [num(r.rup_mag), num(r.dist_rjb), num(r.site_vs30), num(r.pga)]);
const nosofPgv = nosofRows.map((r) => [
  num(r.rup_mag),
  num(r.dist_rjb),
  num(r.site_vs30),
  num(r.pgv),
]);
const std = withRake(stdRows, 'pga');
const stdPgv = withRake(stdRows, 'pgv');
const awwMean = csv('AWW_IPE_RHYPO_MEAN.csv').map((r) => [
  num(r.rup_mag),
  num(r.dist_rhypo),
  num(r.mmi),
]);
const awwSigma = csv('AWW_IPE_RHYPO_SIGMA.csv').map((r) => [
  num(r.rup_mag),
  num(r.dist_rhypo),
  num(r.mmi),
]);

const lines = (rows: number[][]): string => rows.map((r) => `  [${r.join(', ')}],`).join('\n');

const body = `// Generated by scripts/build-openquake-reference.ts. Do not edit by hand.
//
// Values from the test data of the OpenQuake Engine (Copyright (C) GEM
// Foundation; GNU Affero General Public License, version 3 or later):
// openquake/hazardlib/tests/gsim/data/BSSA2014/BSSA_2014_MEAN.csv,
// BSSA_2014_NOSOF_MEAN.csv and BSSA_2014_TOTAL_STD.csv, which OpenQuake
// says were generated from David M. Boore's Fortran implementation of
// Boore et al. 2014 (July 2014); and a12ipe/AWW_IPE_RHYPO_MEAN.csv and
// AWW_IPE_RHYPO_SIGMA.csv, from an independent Matlab implementation of
// Allen, Wald & Worden 2012. Only the PGA, PGV and MMI columns are kept.

/** Boore et al. 2014, global, no basin term, with style of faulting:
 *  magnitude, rake (°), R_JB (km), Vs30 (m/s), median PGA (g). */
// prettier-ignore
export const BSSA14_PGA_MEAN: readonly (readonly [number, number, number, number, number])[] = [
${lines(bssa)}
];

/** The same without style of faulting: magnitude, R_JB (km), Vs30
 *  (m/s), median PGA (g). */
// prettier-ignore
export const BSSA14_PGA_MEAN_UNSPECIFIED: readonly (readonly [number, number, number, number])[] = [
${lines(nosof)}
];

/** Total standard deviation of ln PGA: magnitude, rake (°), R_JB (km),
 *  Vs30 (m/s), σ. */
// prettier-ignore
export const BSSA14_PGA_TOTAL_SIGMA: readonly (readonly [number, number, number, number, number])[] = [
${lines(std)}
];

/** Boore et al. 2014, global, no basin term, with style of faulting:
 *  magnitude, rake (°), R_JB (km), Vs30 (m/s), median PGV (cm/s). */
// prettier-ignore
export const BSSA14_PGV_MEAN: readonly (readonly [number, number, number, number, number])[] = [
${lines(bssaPgv)}
];

/** The same without style of faulting: magnitude, R_JB (km), Vs30
 *  (m/s), median PGV (cm/s). */
// prettier-ignore
export const BSSA14_PGV_MEAN_UNSPECIFIED: readonly (readonly [number, number, number, number])[] = [
${lines(nosofPgv)}
];

/** Total standard deviation of ln PGV: magnitude, rake (°), R_JB (km),
 *  Vs30 (m/s), σ. */
// prettier-ignore
export const BSSA14_PGV_TOTAL_SIGMA: readonly (readonly [number, number, number, number, number])[] = [
${lines(stdPgv)}
];

/** Allen, Wald & Worden 2012, hypocentral form: magnitude, R_hyp (km),
 *  median MMI. */
// prettier-ignore
export const AWW12_RHYPO_MEAN: readonly (readonly [number, number, number])[] = [
${lines(awwMean)}
];

/** The same, total standard deviation of MMI. */
// prettier-ignore
export const AWW12_RHYPO_SIGMA: readonly (readonly [number, number, number])[] = [
${lines(awwSigma)}
];
`;

const out = join(
  resolve(dirname(fileURLToPath(import.meta.url)), '..'),
  'src',
  'physics',
  'validation',
  'openQuakeReference.ts'
);
writeFileSync(out, body);
console.error(
  `wrote ${bssa.length.toString()} + ${nosof.length.toString()} BSSA14 means and ${std.length.toString()} sigmas for PGA and for PGV, ${awwMean.length.toString()} + ${awwSigma.length.toString()} Allen rows → ${out}`
);
