import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { FireballEvent } from '../src/physics/validation/fireballRules.js';

/**
 * The bolides of rule 76 of `src/physics/validation/fireballRules.ts`.
 *
 * NASA JPL's Center for Near-Earth Object Studies publishes, for every
 * fireball its sensors have reported since 1988, the date, the place, the
 * altitude of peak brightness, the pre-entry speed and its components, the
 * radiated energy and the total impact energy. Only the rows that carry an
 * altitude, a speed and an energy can be put to the entry model, and this
 * writes those, less the one the project has read. Nothing here runs Nimbus.
 *
 * Usage:
 *   pnpm exec tsx scripts/build-fireball-set.ts [cache directory]
 *
 * The response is kept in the cache directory, named by the SHA-256 of its
 * URL, as the other set builders keep theirs.
 */

const API = 'https://ssd-api.jpl.nasa.gov/fireball.api?req-loc=false&vel-comp=true&limit=5000';
const CACHE = resolve(process.argv[2] ?? join(tmpdir(), 'nimbus-fireball-set'));

/** Rule 76: the bolides the project has read, taken out. */
const SEEN: readonly { date: string; name: string; seenAs: string }[] = [
  {
    date: '2013-02-15',
    name: 'Chelyabinsk 2013',
    seenAs: 'a preset, whose body is the one Popova et al. 2013 measured (B-033)',
  },
];

interface Fireball {
  signature: { source: string; version: string };
  count: string;
  fields: string[];
  data: (string | null)[][];
}

async function json(url: string): Promise<Fireball> {
  const file = join(CACHE, `${createHash('sha256').update(url).digest('hex')}.json`);
  if (existsSync(file)) return JSON.parse(readFileSync(file, 'utf8')) as Fireball;
  const res = await fetch(url, { headers: { 'User-Agent': 'nimbus-validation' } });
  if (!res.ok) throw new Error(`fetch ${url}: ${res.status.toString()}`);
  const text = await res.text();
  mkdirSync(CACHE, { recursive: true });
  writeFileSync(file, text);
  return JSON.parse(text) as Fireball;
}

const clean = (x: number): number => Number(x.toPrecision(10));

function rowText(r: FireballEvent): string {
  return `  [${JSON.stringify(r.date)}, ${r.latitude.toString()}, ${r.longitude.toString()}, ${r.altitudeKm.toString()}, ${r.speedKmS.toString()}, ${r.energyKt.toString()}, ${r.vxKmS.toString()}, ${r.vyKmS.toString()}, ${r.vzKmS.toString()}],`;
}

async function main(): Promise<void> {
  const response = await json(API);
  const at = (field: string): number => response.fields.indexOf(field);
  const iDate = at('date');
  const iEnergy = at('impact-e');
  const iLat = at('lat');
  const iLatDir = at('lat-dir');
  const iLon = at('lon');
  const iLonDir = at('lon-dir');
  const iAlt = at('alt');
  const iVel = at('vel');
  const iVx = at('vx');
  const iVy = at('vy');
  const iVz = at('vz');
  const rows: FireballEvent[] = [];
  let withoutAltitude = 0;
  let withoutSpeed = 0;
  let withoutPlace = 0;
  const seen: string[] = [];
  for (const row of response.data) {
    const value = (i: number): number | null => {
      const raw = row[i];
      return raw === null || raw === undefined || raw === '' ? null : Number(raw);
    };
    const date = row[iDate] ?? '';
    const altitudeKm = value(iAlt);
    const speedKmS = value(iVel);
    const energyKt = value(iEnergy);
    const latitude = value(iLat);
    const longitude = value(iLon);
    if (altitudeKm === null) {
      withoutAltitude += 1;
      continue;
    }
    if (speedKmS === null || value(iVx) === null) {
      withoutSpeed += 1;
      continue;
    }
    if (energyKt === null || latitude === null || longitude === null) {
      withoutPlace += 1;
      continue;
    }
    if (SEEN.some((s) => date.startsWith(s.date))) {
      seen.push(date);
      continue;
    }
    const sign = (v: number, dir: string | null | undefined, negative: string): number =>
      dir === negative ? -v : v;
    rows.push({
      date: date.replace(' ', 'T') + 'Z',
      latitude: clean(sign(latitude, row[iLatDir], 'S')),
      longitude: clean(sign(longitude, row[iLonDir], 'W')),
      altitudeKm: clean(altitudeKm),
      speedKmS: clean(speedKmS),
      energyKt: clean(energyKt),
      vxKmS: clean(value(iVx) ?? 0),
      vyKmS: clean(value(iVy) ?? 0),
      vzKmS: clean(value(iVz) ?? 0),
    });
  }
  rows.sort((a, b) => (a.date < b.date ? -1 : 1));
  const readOn = new Date().toISOString().slice(0, 10);
  const body = `// Generated by scripts/build-fireball-set.ts on ${readOn}. Do not edit by
// hand: rule 76 of fireballRules.ts says what these are and how they were
// read. NASA/JPL Center for Near-Earth Object Studies, Fireball Data API
// ${response.signature.version} (https://ssd-api.jpl.nasa.gov/doc/fireball.html), public domain.

import type { FireballEvent } from './fireballRules.js';

export const FIREBALL_READ_ON = '${readOn}';

/** Bolides the API returned that day, before the rows without an altitude,
 *  a speed or a place were left out. */
export const FIREBALL_LISTED = ${response.data.length.toString()};

/** Rows left out: no altitude of peak brightness, no pre-entry speed or
 *  velocity components, and no energy or place. */
export const FIREBALL_WITHOUT_ALTITUDE = ${withoutAltitude.toString()};
export const FIREBALL_WITHOUT_SPEED = ${withoutSpeed.toString()};
export const FIREBALL_WITHOUT_PLACE = ${withoutPlace.toString()};

/** Rows left out because the project has read them (rule 76). */
export const FIREBALL_SEEN: readonly string[] = ${JSON.stringify(seen)};

type Line = readonly [string, number, number, number, number, number, number, number, number];

const fireball = ([
  date, latitude, longitude, altitudeKm, speedKmS, energyKt, vxKmS, vyKmS, vzKmS,
]: Line): FireballEvent => ({
  date, latitude, longitude, altitudeKm, speedKmS, energyKt, vxKmS, vyKmS, vzKmS,
});

/** Columns: date (UTC), latitude and longitude (°, south and west
 *  negative), altitude of peak brightness (km), pre-entry speed (km/s),
 *  total impact energy (kt of TNT), and the speed's components in the
 *  Earth-centred frame the API gives them in (km/s). */
// prettier-ignore
const LINES: readonly Line[] = [
${rows.map(rowText).join('\n')}
];

export const FIREBALL_EVENTS: readonly FireballEvent[] = LINES.map(fireball);
`;
  const out = join(
    resolve(dirname(fileURLToPath(import.meta.url)), '..'),
    'src',
    'physics',
    'validation',
    'fireballSetData.ts'
  );
  writeFileSync(out, body);
  console.error(
    `listed ${response.data.length.toString()}: wrote ${rows.length.toString()}, ${withoutAltitude.toString()} without altitude, ${withoutSpeed.toString()} without speed, ${withoutPlace.toString()} without energy or place, ${seen.length.toString()} already read → ${out}`
  );
}

await main();
