import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * The USGS PAGER loss products the benchmark campaign read for its
 * EQ-PAGER track, for rules 31 to 34 of
 * `src/physics/validation/pagerChain.ts`.
 *
 * Reads the file `scripts/benchmark/pager-bench.ts` wrote — one ComCat
 * `losspager` product per line — and keeps, for every earthquake whose
 * product carries both a population exposure and an empirical fatality
 * estimate, what the rules score against: the population PAGER puts in
 * each intensity bin, its fatality estimate, its alert and its maximum
 * intensity. Nothing here runs the simulator.
 *
 * Usage:
 *   pnpm exec tsx scripts/build-pager-products.ts <pager.jsonl> <read on, YYYY-MM-DD>
 *
 * PAGER revises its products, so a run of pager-bench.ts on another day
 * can write different numbers; the file in the repository is the one the
 * rules were applied to, and it records the day the products were read.
 */

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'src', 'physics', 'validation', 'pagerProductsData.ts');

interface Line {
  comcat: string;
  status: string;
  alertlevel?: string | null;
  maxmmi?: string | null;
  exposures?: { population_exposure?: { mmi: number[]; aggregated_exposure: number[] } } | null;
  losses?: { empirical_fatality?: { total_fatalities: number } } | null;
}

const [path, readOn] = process.argv.slice(2);
if (path === undefined || readOn === undefined || !/^\d{4}-\d{2}-\d{2}$/.test(readOn)) {
  throw new Error('usage: build-pager-products.ts <pager.jsonl> <YYYY-MM-DD>');
}

const rows = readFileSync(path, 'utf8')
  .split('\n')
  .filter((l) => l.trim() !== '')
  .map((l) => JSON.parse(l) as Line)
  .flatMap((line) => {
    const exposure = line.exposures?.population_exposure;
    const fatalities = line.losses?.empirical_fatality?.total_fatalities;
    if (line.status !== 'ok' || exposure === undefined || fatalities === undefined) return [];
    // PAGER's bins are intensities 1 to 10, in that order.
    const bins = Array.from({ length: 10 }, (_, k) => {
      const at = exposure.mmi.indexOf(k + 1);
      return at < 0 ? 0 : Math.round(exposure.aggregated_exposure[at] ?? 0);
    });
    return [
      {
        comcat: line.comcat,
        alert: line.alertlevel ?? null,
        maxMmi: Number(line.maxmmi ?? 'NaN'),
        exposure: bins,
        fatalities: Math.round(fatalities),
      },
    ];
  });

const body = `// Generated by scripts/build-pager-products.ts from the products
// scripts/benchmark/pager-bench.ts read on ${readOn}. Do not edit by hand:
// rules 31 to 34 of pagerChain.ts say what these are and how they are
// scored. USGS PAGER (ComCat losspager products), public domain.

import type { PagerProduct } from './pagerChain.js';

export const PAGER_PRODUCTS_READ_ON = '${readOn}';

export const PAGER_PRODUCTS: readonly PagerProduct[] = [
${rows
  .map(
    (r) =>
      `  { comcat: '${r.comcat}', alert: ${r.alert === null ? 'null' : `'${r.alert}'`}, maxMmi: ${Number.isFinite(r.maxMmi) ? r.maxMmi.toString() : 'Number.NaN'}, exposure: [${r.exposure.join(', ')}], fatalities: ${r.fatalities.toString()} },`
  )
  .join('\n')}
];
`;

writeFileSync(OUT, body);
console.log(`${rows.length.toString()} products written to ${OUT}`);
