import type { JSX } from 'react';
import { useTranslation } from 'react-i18next';
import styles from './TollChart.module.css';

/** One quantity of the comparison against the reference program. */
export interface ProgramChartRow {
  quantity: string;
  pairs: number;
  geometricMean: number;
  p10: number;
  p90: number;
}

// Drawing units, as in the toll chart beside it: the SVG scales through its
// viewBox, and on a narrow screen the figure scrolls sideways inside its own
// frame rather than shrinking its labels below legibility.
const WIDTH = 980;
const ROW = 30;
const LABEL = 300; // column of quantity names
const PAIRS = 96; // column of "n cases"
const TOP = 12;
const AXIS = 30;

/**
 * Figure 2 of the landing page: quantity by quantity, how the impact
 * pipeline answers against the Earth Impact Effects Program (Collins, Melosh
 * & Marcus 2005) run by its authors — the reference implementation of the
 * equations this model cites.
 *
 * The bar is the tenth to the ninetieth percentile of the ratio Nimbus /
 * program over the cases of the grid; the dot is the geometric mean. One is
 * agreement to the last printed digit. This says the equations are
 * implemented as their authors wrote them; it does not say the equations
 * describe the world — what does that is measured against observations, and
 * for an impact the world has left very little to measure.
 *
 * The rows come from docs/VALIDATION_REPORT.json, regenerated by the CI from
 * the code of the commit that built the page.
 */
export function ProgramChart({ rows }: { rows: ProgramChartRow[] }): JSX.Element {
  const { t, i18n } = useTranslation();
  const locale = i18n.language.toLowerCase().startsWith('it') ? 'it-IT' : 'en-US';
  const sorted = [...rows].sort((a, b) => b.pairs - a.pairs);

  const lo = Math.min(0.97, ...rows.map((r) => r.p10));
  const hi = Math.max(1.03, ...rows.map((r) => r.p90));
  const plotStart = LABEL + 16;
  const plotEnd = WIDTH - PAIRS - 12;
  const x = (v: number): number => plotStart + ((v - lo) / (hi - lo)) * (plotEnd - plotStart);
  const height = TOP + ROW * sorted.length + AXIS;
  const plotBottom = TOP + ROW * sorted.length;
  const ratio = (v: number): string =>
    `${v.toLocaleString(locale, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}×`;
  // Whole percentage points, so the axis reads 0.97×, 0.98×, … and never
  // prints two labels a hair apart.
  const first = Math.floor(lo * 100) / 100;
  const last = Math.ceil(hi * 100) / 100;
  const ticks = Array.from(
    { length: Math.round((last - first) * 100) + 1 },
    (_, i) => Math.round((first + i / 100) * 100) / 100
  ).filter((v) => v >= lo && v <= hi);

  return (
    <div className={styles.chart}>
      <ul className={styles.legend} aria-hidden="true">
        <li>
          <span className={styles.keyBand} />
          {t('landing.validation.legendSpread')}
        </li>
        <li>
          <span className={styles.keyModel} />
          {t('landing.validation.legendRatio')}
        </li>
        <li>
          <span className={styles.keyRecorded} />
          {t('landing.validation.legendAgreement')}
        </li>
      </ul>

      <div
        className={styles.scroll}
        // eslint-disable-next-line jsx-a11y/no-noninteractive-tabindex
        tabIndex={0}
        role="group"
        aria-label={t('landing.validation.chartRegion')}
      >
        <svg
          className={styles.svg}
          viewBox={`0 0 ${String(WIDTH)} ${String(height)}`}
          aria-hidden="true"
          focusable="false"
        >
          {ticks.map((v) => (
            <g key={v}>
              <line className={styles.grid} x1={x(v)} x2={x(v)} y1={TOP - 4} y2={plotBottom} />
              <text className={styles.tick} x={x(v)} y={plotBottom + 18} textAnchor="middle">
                {ratio(v)}
              </text>
            </g>
          ))}

          {sorted.map((r, i) => {
            const cy = TOP + ROW * i + ROW / 2;
            const a = x(r.p10);
            const b = x(r.p90);
            return (
              <g key={r.quantity}>
                {i % 2 === 0 && (
                  <rect
                    className={styles.stripe}
                    x={0}
                    y={cy - ROW / 2}
                    width={WIDTH}
                    height={ROW}
                  />
                )}
                <text className={styles.name} x={LABEL - 14} y={cy + 4} textAnchor="end">
                  {t(`landing.validation.quantities.${r.quantity}`)}
                </text>
                <rect
                  className={styles.band}
                  x={a}
                  y={cy - 4}
                  width={Math.max(b - a, 8)}
                  height={8}
                  rx={4}
                />
                {/* Agreement to the last digit: the line the dots should sit on. */}
                <rect
                  className={styles.recorded}
                  x={x(1) - 1.25}
                  y={cy - 8}
                  width={2.5}
                  height={16}
                  rx={1}
                />
                <circle className={styles.model} cx={x(r.geometricMean)} cy={cy} r={5} />
                <text className={styles.tick} x={WIDTH - 8} y={cy + 4} textAnchor="end">
                  {r.pairs.toLocaleString(locale)}
                </text>
              </g>
            );
          })}
        </svg>
      </div>
      <p className={styles.axisLabel} aria-hidden="true">
        {t('landing.validation.axisRatio')}
      </p>

      {/* The same numbers as a table, for screen readers. */}
      <div className={styles.srOnly}>
        <table>
          <caption>{t('landing.validation.tableProgramCaption')}</caption>
          <thead>
            <tr>
              <th scope="col">{t('landing.validation.tableQuantity')}</th>
              <th scope="col">{t('landing.validation.tableCases')}</th>
              <th scope="col">{t('landing.validation.tableRatio')}</th>
              <th scope="col">{t('landing.validation.tableSpread')}</th>
            </tr>
          </thead>
          <tbody>
            {sorted.map((r) => (
              <tr key={r.quantity}>
                <th scope="row">{t(`landing.validation.quantities.${r.quantity}`)}</th>
                <td>{r.pairs.toLocaleString(locale)}</td>
                <td>{ratio(r.geometricMean)}</td>
                <td>
                  {ratio(r.p10)}–{ratio(r.p90)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
