/**
 * The gate learns to read what the audits already write.
 *
 * The release gate is four things: a replay failure, a golden failure, a gated
 * death-toll row missing its record, a gated wave row missing its record. None
 * of them is a picture, and none of them is a terrain.
 *
 * Meanwhile two audits run and write what they find:
 *
 *   scripts/benchmark/globe-audit.ts reads what the renderer hands Cesium for
 *   thirty scenarios — every ellipse's axes, centre, rotation and caption,
 *   beside the numbers the store holds — and writes
 *   benchmark/results/globe-audit-<date>.json, which is committed. The
 *   validation report names that file in a sentence of prose. The generator
 *   never opens it.
 *
 *   scripts/benchmark/shore-distance.ts drives the product at four points
 *   whose geography is known and reads what the store derives for them, against
 *   bounds fixed by rules 243 and 250(b). Nothing reads its output at all,
 *   because it does not write one.
 *
 * What that cost, in one day. Six defects of 19 September 2026 were invisible
 * to the gate for exactly this reason: B-058 and B-060, a legend stating a
 * number the globe did not draw; B-059, a shape covering more ground than its
 * caption; B-068, a shore at nought metres from a cell 39 km wide; B-069,
 * every coast on Earth two hundred metres deep; B-073, a wave justified by a
 * hole in water that is not there. Four of the six were found by a reader
 * looking at a report of his own and not believing it. The gate passed on all
 * of them, every time, and would pass on the next one.
 *
 * What was looked at before these rules were written, and is therefore not
 * held out: the `gate` function and its four arms; the shape of the globe
 * audit's JSON; that `shore-distance.ts` prints and does not write; and the
 * six registry rows above.
 *
 * The rules, fixed on 20 September 2026, before the candidate was written, and
 * numbered after the two hundred and seventy-three before them:
 *
 * 274. The candidate. The report's generator reads both artefacts, prints what
 *      they say, and the gate blocks on: any finding in the globe audit; any
 *      terrain row outside the bounds of rules 243 and 250(b); and either
 *      artefact missing or unreadable. `shore-distance.ts` gains a written
 *      output so there is something to read.
 *
 * 275. What still does not block, said rather than hidden: a silence. The
 *      globe audit's six — the landslide's own length, published and undrawn —
 *      are the picture saying nothing rather than something false, and gating
 *      on them would make every published quantity that nothing draws a
 *      release blocker. They are printed and counted, and the count is in the
 *      report where a reader trips over it.
 *
 * 276. Staleness, and what is NOT claimed. Neither artefact is regenerated by
 *      the gate: each is produced by the round that needs it and committed,
 *      as the globe audit has been all along. The generator reads the newest
 *      by name, prints which file it read, and blocks when there is none. It
 *      does not check whether the file is older than the code it describes —
 *      that wants a fingerprint of everything a picture depends on, and
 *      inventing one here would be a promise the project cannot keep. The
 *      discipline stays where it is: a round that touches the map or the
 *      terrain re-runs its audit before it commits.
 *
 * 277. What decides. Exact and mechanical, since this is a gate and not a
 *      measurement:
 *      (a) fed an artefact with a finding, the gate blocks and names it;
 *      (b) fed an artefact with a terrain row outside its bounds, the same;
 *      (c) fed no artefact at all, the same;
 *      (d) fed the artefacts as they stand, the gate passes and the four arms
 *          it already had are unchanged;
 *      (e) the verdict on the tree as it stands is still PASS, and no toll,
 *          wave, replay or golden figure moves by anything.
 *
 * 278. What may not happen. No artefact is regenerated to make the gate pass,
 *      and no bound is widened. If the gate blocks on the tree as it stands,
 *      that is the finding and the round stops to fix it.
 *
 * What these rules cannot settle. Whether an artefact describes the code it
 * sits beside — rule 276 says plainly that nothing here checks it. Whether
 * thirty scenarios and four points are enough of either. And the deeper thing
 * the six defects have in common, which no gate closes: the calibration net
 * has no impact row at all, because no impact in history left a death toll to
 * compare, so an impact's whole chain is gated by the field's own program and
 * by nothing from the world.
 */

/** Where the two audits write, relative to the repository root. */
export const AUDIT_ARTEFACTS = {
  globe: { directory: 'benchmark/results', prefix: 'globe-audit-' },
  terrain: { directory: 'benchmark/results', prefix: 'terrain-derivation-' },
} as const;

/** A terrain row as `shore-distance.ts` writes it. */
export interface TerrainDerivationRow {
  name: string;
  latitude: number;
  longitude: number;
  shoreDistanceM: number | null;
  waterDepthM: number | null;
  shoreInsideBounds: boolean;
  depthInsideBounds: boolean;
}

/** What that script writes, in full. */
export interface TerrainDerivationArtefact {
  base: string;
  rows: TerrainDerivationRow[];
}

/** Rule 274: the rows a gate blocks on, and why, or an empty list. */
export function terrainGateProblems(artefact: TerrainDerivationArtefact): string[] {
  const out: string[] = [];
  for (const row of artefact.rows) {
    if (!row.shoreInsideBounds) out.push(`${row.name}: shore distance outside rule 243's bounds`);
    if (!row.depthInsideBounds) out.push(`${row.name}: shore depth outside rule 250(b)'s bound`);
  }
  return out;
}

/**
 * The outcome of the round, written after the candidate was measured and not
 * before. Left null until then, so a reader can tell a rule from a result.
 */
export const GATE_READS_OUTCOME: string | null = null;
