/* Generated by scripts/benchmark/kb-grid.py — do not edit by hand.
 *
 * The incident pressure of a hemispherical TNT surface burst, as an
 * implementation of Kingery–Bulmash independent of this project answers for it:
 * the MIT-licensed `kingery-bulmash` package (github.com/fcento100/kingery-bulmash),
 * which implements Swisdak's (1994) simplified fits, run as a black box on
 * 488 points — 8 charges from 1 kg to 1 kt, at 61 scaled
 * distances from 0.2 to 40.0 m·kg⁻¹ᐟ³ each.
 *
 * Before the grid, the package is held to the three worked examples IATG 01.80
 * (2021) Table 5 prints, which come from the original 1984 polynomials:
 * +0.53 %, +0.07 %, +0.46 %.
 *
 * `effects/kingeryBulmash.test.ts` holds the model to these points. The model
 * is written from Swisdak's paper (rules 177 to 181 of
 * validation/chemicalBlastRules.ts), not from this package.
 */

export interface KingeryBulmashPoint {
  /** Charge, in kilogrammes of TNT. */
  readonly chargeKg: number;
  /** Scaled distance, m·kg⁻¹ᐟ³. */
  readonly scaled: number;
  /** Peak incident overpressure, kPa. */
  readonly kPa: number;
}

/** The package's answer at each point of the grid. */
export const KINGERY_BULMASH_GRID: readonly KingeryBulmashPoint[] = [
  {
    chargeKg: 1,
    scaled: 0.2,
    kPa: 17310.35998012716,
  },
  {
    chargeKg: 1,
    scaled: 0.218464,
    kPa: 15397.0000120463,
  },
  {
    chargeKg: 1,
    scaled: 0.238633,
    kPa: 13720.545972797197,
  },
  {
    chargeKg: 1,
    scaled: 0.260664,
    kPa: 12234.500181703123,
  },
  {
    chargeKg: 1,
    scaled: 0.284729,
    kPa: 10904.313334952703,
  },
  {
    chargeKg: 1,
    scaled: 0.311016,
    kPa: 9704.401958115983,
  },
  {
    chargeKg: 1,
    scaled: 0.339729,
    kPa: 8615.929178570845,
  },
  {
    chargeKg: 1,
    scaled: 0.371094,
    kPa: 7625.113165942521,
  },
  {
    chargeKg: 1,
    scaled: 0.405354,
    kPa: 6721.90933246499,
  },
  {
    chargeKg: 1,
    scaled: 0.442776,
    kPa: 5898.9669004255775,
  },
  {
    chargeKg: 1,
    scaled: 0.483654,
    kPa: 5150.796639536427,
  },
  {
    chargeKg: 1,
    scaled: 0.528306,
    kPa: 4473.110025053239,
  },
  {
    chargeKg: 1,
    scaled: 0.57708,
    kPa: 3862.3044261384166,
  },
  {
    chargeKg: 1,
    scaled: 0.630357,
    kPa: 3315.0767923078415,
  },
  {
    chargeKg: 1,
    scaled: 0.688552,
    kPa: 2828.1516595160238,
  },
  {
    chargeKg: 1,
    scaled: 0.752121,
    kPa: 2398.1097864251446,
  },
  {
    chargeKg: 1,
    scaled: 0.821558,
    kPa: 2021.3027266722509,
  },
  {
    chargeKg: 1,
    scaled: 0.897405,
    kPa: 1693.8372497003234,
  },
  {
    chargeKg: 1,
    scaled: 0.980255,
    kPa: 1411.6125518903814,
  },
  {
    chargeKg: 1,
    scaled: 1.070753,
    kPa: 1170.3931461092895,
  },
  {
    chargeKg: 1,
    scaled: 1.169607,
    kPa: 965.9013674702634,
  },
  {
    chargeKg: 1,
    scaled: 1.277587,
    kPa: 793.9155074145746,
  },
  {
    chargeKg: 1,
    scaled: 1.395536,
    kPa: 650.3624179015258,
  },
  {
    chargeKg: 1,
    scaled: 1.524374,
    kPa: 531.396642330283,
  },
  {
    chargeKg: 1,
    scaled: 1.665106,
    kPa: 433.46134610877033,
  },
  {
    chargeKg: 1,
    scaled: 1.818832,
    kPa: 353.329210453883,
  },
  {
    chargeKg: 1,
    scaled: 1.986749,
    kPa: 288.1237912729341,
  },
  {
    chargeKg: 1,
    scaled: 2.170169,
    kPa: 235.32351964287713,
  },
  {
    chargeKg: 1,
    scaled: 2.370522,
    kPa: 192.75152700306094,
  },
  {
    chargeKg: 1,
    scaled: 2.589372,
    kPa: 158.55489400866523,
  },
  {
    chargeKg: 1,
    scaled: 2.828427,
    kPa: 131.17687416700196,
  },
  {
    chargeKg: 1,
    scaled: 3.089552,
    kPa: 108.75345140657056,
  },
  {
    chargeKg: 1,
    scaled: 3.374784,
    kPa: 90.61920068285787,
  },
  {
    chargeKg: 1,
    scaled: 3.686349,
    kPa: 75.97233086823113,
  },
  {
    chargeKg: 1,
    scaled: 4.026679,
    kPa: 64.07386606527938,
  },
  {
    chargeKg: 1,
    scaled: 4.398428,
    kPa: 54.35266463928048,
  },
  {
    chargeKg: 1,
    scaled: 4.804498,
    kPa: 46.36511412903269,
  },
  {
    chargeKg: 1,
    scaled: 5.248056,
    kPa: 39.764957855049715,
  },
  {
    chargeKg: 1,
    scaled: 5.732565,
    kPa: 34.28060744224936,
  },
  {
    chargeKg: 1,
    scaled: 6.261804,
    kPa: 29.69800929554826,
  },
  {
    chargeKg: 1,
    scaled: 6.839904,
    kPa: 25.84764884117839,
  },
  {
    chargeKg: 1,
    scaled: 7.471374,
    kPa: 22.594650362540467,
  },
  {
    chargeKg: 1,
    scaled: 8.161143,
    kPa: 19.831202468745733,
  },
  {
    chargeKg: 1,
    scaled: 8.914592,
    kPa: 17.47073807926481,
  },
  {
    chargeKg: 1,
    scaled: 9.737601,
    kPa: 15.443443601628044,
  },
  {
    chargeKg: 1,
    scaled: 10.636592,
    kPa: 13.692779273577624,
  },
  {
    chargeKg: 1,
    scaled: 11.618578,
    kPa: 12.172771896964967,
  },
  {
    chargeKg: 1,
    scaled: 12.691223,
    kPa: 10.845899952350555,
  },
  {
    chargeKg: 1,
    scaled: 13.862897,
    kPa: 9.681434810626476,
  },
  {
    chargeKg: 1,
    scaled: 15.142741,
    kPa: 8.65413441649322,
  },
  {
    chargeKg: 1,
    scaled: 16.540742,
    kPa: 7.743210298952623,
  },
  {
    chargeKg: 1,
    scaled: 18.067809,
    kPa: 6.931507181495348,
  },
  {
    chargeKg: 1,
    scaled: 19.735857,
    kPa: 6.204848373748006,
  },
  {
    chargeKg: 1,
    scaled: 21.557902,
    kPa: 5.5515106742244225,
  },
  {
    chargeKg: 1,
    scaled: 23.548161,
    kPa: 4.961800551203858,
  },
  {
    chargeKg: 1,
    scaled: 25.722163,
    kPa: 4.4188225115288935,
  },
  {
    chargeKg: 1,
    scaled: 28.096873,
    kPa: 3.902678219361163,
  },
  {
    chargeKg: 1,
    scaled: 30.69082,
    kPa: 3.4468225967750477,
  },
  {
    chargeKg: 1,
    scaled: 33.524244,
    kPa: 3.0442135748470207,
  },
  {
    chargeKg: 1,
    scaled: 36.619254,
    kPa: 2.688631639456465,
  },
  {
    chargeKg: 1,
    scaled: 40.0,
    kPa: 2.3745837520777826,
  },
  {
    chargeKg: 10,
    scaled: 0.2,
    kPa: 17310.35998012716,
  },
  {
    chargeKg: 10,
    scaled: 0.218464,
    kPa: 15397.0000120463,
  },
  {
    chargeKg: 10,
    scaled: 0.238633,
    kPa: 13720.545972797197,
  },
  {
    chargeKg: 10,
    scaled: 0.260664,
    kPa: 12234.500181703123,
  },
  {
    chargeKg: 10,
    scaled: 0.284729,
    kPa: 10904.313334952703,
  },
  {
    chargeKg: 10,
    scaled: 0.311016,
    kPa: 9704.401958115983,
  },
  {
    chargeKg: 10,
    scaled: 0.339729,
    kPa: 8615.929178570845,
  },
  {
    chargeKg: 10,
    scaled: 0.371094,
    kPa: 7625.113165942521,
  },
  {
    chargeKg: 10,
    scaled: 0.405354,
    kPa: 6721.90933246499,
  },
  {
    chargeKg: 10,
    scaled: 0.442776,
    kPa: 5898.9669004255775,
  },
  {
    chargeKg: 10,
    scaled: 0.483654,
    kPa: 5150.796639536427,
  },
  {
    chargeKg: 10,
    scaled: 0.528306,
    kPa: 4473.110025053239,
  },
  {
    chargeKg: 10,
    scaled: 0.57708,
    kPa: 3862.3044261384166,
  },
  {
    chargeKg: 10,
    scaled: 0.630357,
    kPa: 3315.0767923078415,
  },
  {
    chargeKg: 10,
    scaled: 0.688552,
    kPa: 2828.1516595160238,
  },
  {
    chargeKg: 10,
    scaled: 0.752121,
    kPa: 2398.1097864251446,
  },
  {
    chargeKg: 10,
    scaled: 0.821558,
    kPa: 2021.3027266722509,
  },
  {
    chargeKg: 10,
    scaled: 0.897405,
    kPa: 1693.8372497003234,
  },
  {
    chargeKg: 10,
    scaled: 0.980255,
    kPa: 1411.61255189038,
  },
  {
    chargeKg: 10,
    scaled: 1.070753,
    kPa: 1170.3931461092895,
  },
  {
    chargeKg: 10,
    scaled: 1.169607,
    kPa: 965.9013674702634,
  },
  {
    chargeKg: 10,
    scaled: 1.277587,
    kPa: 793.9155074145746,
  },
  {
    chargeKg: 10,
    scaled: 1.395536,
    kPa: 650.3624179015258,
  },
  {
    chargeKg: 10,
    scaled: 1.524374,
    kPa: 531.396642330283,
  },
  {
    chargeKg: 10,
    scaled: 1.665106,
    kPa: 433.46134610877033,
  },
  {
    chargeKg: 10,
    scaled: 1.818832,
    kPa: 353.329210453883,
  },
  {
    chargeKg: 10,
    scaled: 1.986749,
    kPa: 288.1237912729341,
  },
  {
    chargeKg: 10,
    scaled: 2.170169,
    kPa: 235.32351964287713,
  },
  {
    chargeKg: 10,
    scaled: 2.370522,
    kPa: 192.75152700306094,
  },
  {
    chargeKg: 10,
    scaled: 2.589372,
    kPa: 158.55489400866523,
  },
  {
    chargeKg: 10,
    scaled: 2.828427,
    kPa: 131.17687416700196,
  },
  {
    chargeKg: 10,
    scaled: 3.089552,
    kPa: 108.75345140657056,
  },
  {
    chargeKg: 10,
    scaled: 3.374784,
    kPa: 90.61920068285787,
  },
  {
    chargeKg: 10,
    scaled: 3.686349,
    kPa: 75.97233086823113,
  },
  {
    chargeKg: 10,
    scaled: 4.026679,
    kPa: 64.07386606527938,
  },
  {
    chargeKg: 10,
    scaled: 4.398428,
    kPa: 54.35266463928048,
  },
  {
    chargeKg: 10,
    scaled: 4.804498,
    kPa: 46.36511412903269,
  },
  {
    chargeKg: 10,
    scaled: 5.248056,
    kPa: 39.764957855049715,
  },
  {
    chargeKg: 10,
    scaled: 5.732565,
    kPa: 34.28060744224936,
  },
  {
    chargeKg: 10,
    scaled: 6.261804,
    kPa: 29.69800929554826,
  },
  {
    chargeKg: 10,
    scaled: 6.839904,
    kPa: 25.84764884117839,
  },
  {
    chargeKg: 10,
    scaled: 7.471374,
    kPa: 22.594650362540467,
  },
  {
    chargeKg: 10,
    scaled: 8.161143,
    kPa: 19.831202468745733,
  },
  {
    chargeKg: 10,
    scaled: 8.914592,
    kPa: 17.47073807926481,
  },
  {
    chargeKg: 10,
    scaled: 9.737601,
    kPa: 15.443443601628044,
  },
  {
    chargeKg: 10,
    scaled: 10.636592,
    kPa: 13.692779273577624,
  },
  {
    chargeKg: 10,
    scaled: 11.618578,
    kPa: 12.172771896964967,
  },
  {
    chargeKg: 10,
    scaled: 12.691223,
    kPa: 10.845899952350555,
  },
  {
    chargeKg: 10,
    scaled: 13.862897,
    kPa: 9.681434810626476,
  },
  {
    chargeKg: 10,
    scaled: 15.142741,
    kPa: 8.65413441649322,
  },
  {
    chargeKg: 10,
    scaled: 16.540742,
    kPa: 7.743210298952623,
  },
  {
    chargeKg: 10,
    scaled: 18.067809,
    kPa: 6.931507181495348,
  },
  {
    chargeKg: 10,
    scaled: 19.735857,
    kPa: 6.204848373748006,
  },
  {
    chargeKg: 10,
    scaled: 21.557902,
    kPa: 5.5515106742244225,
  },
  {
    chargeKg: 10,
    scaled: 23.548161,
    kPa: 4.961800551203858,
  },
  {
    chargeKg: 10,
    scaled: 25.722163,
    kPa: 4.4188225115288935,
  },
  {
    chargeKg: 10,
    scaled: 28.096873,
    kPa: 3.902678219361163,
  },
  {
    chargeKg: 10,
    scaled: 30.69082,
    kPa: 3.4468225967750477,
  },
  {
    chargeKg: 10,
    scaled: 33.524244,
    kPa: 3.0442135748470207,
  },
  {
    chargeKg: 10,
    scaled: 36.619254,
    kPa: 2.688631639456465,
  },
  {
    chargeKg: 10,
    scaled: 40.0,
    kPa: 2.3745837520777826,
  },
  {
    chargeKg: 100,
    scaled: 0.2,
    kPa: 17310.35998012716,
  },
  {
    chargeKg: 100,
    scaled: 0.218464,
    kPa: 15397.0000120463,
  },
  {
    chargeKg: 100,
    scaled: 0.238633,
    kPa: 13720.545972797197,
  },
  {
    chargeKg: 100,
    scaled: 0.260664,
    kPa: 12234.500181703123,
  },
  {
    chargeKg: 100,
    scaled: 0.284729,
    kPa: 10904.313334952703,
  },
  {
    chargeKg: 100,
    scaled: 0.311016,
    kPa: 9704.401958115983,
  },
  {
    chargeKg: 100,
    scaled: 0.339729,
    kPa: 8615.929178570845,
  },
  {
    chargeKg: 100,
    scaled: 0.371094,
    kPa: 7625.113165942521,
  },
  {
    chargeKg: 100,
    scaled: 0.405354,
    kPa: 6721.90933246499,
  },
  {
    chargeKg: 100,
    scaled: 0.442776,
    kPa: 5898.9669004255775,
  },
  {
    chargeKg: 100,
    scaled: 0.483654,
    kPa: 5150.796639536427,
  },
  {
    chargeKg: 100,
    scaled: 0.528306,
    kPa: 4473.110025053239,
  },
  {
    chargeKg: 100,
    scaled: 0.57708,
    kPa: 3862.3044261384166,
  },
  {
    chargeKg: 100,
    scaled: 0.630357,
    kPa: 3315.0767923078415,
  },
  {
    chargeKg: 100,
    scaled: 0.688552,
    kPa: 2828.1516595160238,
  },
  {
    chargeKg: 100,
    scaled: 0.752121,
    kPa: 2398.1097864251446,
  },
  {
    chargeKg: 100,
    scaled: 0.821558,
    kPa: 2021.3027266722509,
  },
  {
    chargeKg: 100,
    scaled: 0.897405,
    kPa: 1693.8372497003234,
  },
  {
    chargeKg: 100,
    scaled: 0.980255,
    kPa: 1411.6125518903814,
  },
  {
    chargeKg: 100,
    scaled: 1.070753,
    kPa: 1170.3931461092895,
  },
  {
    chargeKg: 100,
    scaled: 1.169607,
    kPa: 965.9013674702634,
  },
  {
    chargeKg: 100,
    scaled: 1.277587,
    kPa: 793.9155074145746,
  },
  {
    chargeKg: 100,
    scaled: 1.395536,
    kPa: 650.3624179015258,
  },
  {
    chargeKg: 100,
    scaled: 1.524374,
    kPa: 531.396642330283,
  },
  {
    chargeKg: 100,
    scaled: 1.665106,
    kPa: 433.46134610877033,
  },
  {
    chargeKg: 100,
    scaled: 1.818832,
    kPa: 353.329210453883,
  },
  {
    chargeKg: 100,
    scaled: 1.986749,
    kPa: 288.1237912729341,
  },
  {
    chargeKg: 100,
    scaled: 2.170169,
    kPa: 235.32351964287713,
  },
  {
    chargeKg: 100,
    scaled: 2.370522,
    kPa: 192.75152700306094,
  },
  {
    chargeKg: 100,
    scaled: 2.589372,
    kPa: 158.55489400866523,
  },
  {
    chargeKg: 100,
    scaled: 2.828427,
    kPa: 131.17687416700196,
  },
  {
    chargeKg: 100,
    scaled: 3.089552,
    kPa: 108.75345140657056,
  },
  {
    chargeKg: 100,
    scaled: 3.374784,
    kPa: 90.61920068285787,
  },
  {
    chargeKg: 100,
    scaled: 3.686349,
    kPa: 75.9723308682312,
  },
  {
    chargeKg: 100,
    scaled: 4.026679,
    kPa: 64.07386606527938,
  },
  {
    chargeKg: 100,
    scaled: 4.398428,
    kPa: 54.35266463928048,
  },
  {
    chargeKg: 100,
    scaled: 4.804498,
    kPa: 46.36511412903269,
  },
  {
    chargeKg: 100,
    scaled: 5.248056,
    kPa: 39.764957855049715,
  },
  {
    chargeKg: 100,
    scaled: 5.732565,
    kPa: 34.28060744224936,
  },
  {
    chargeKg: 100,
    scaled: 6.261804,
    kPa: 29.69800929554826,
  },
  {
    chargeKg: 100,
    scaled: 6.839904,
    kPa: 25.84764884117839,
  },
  {
    chargeKg: 100,
    scaled: 7.471374,
    kPa: 22.594650362540467,
  },
  {
    chargeKg: 100,
    scaled: 8.161143,
    kPa: 19.831202468745733,
  },
  {
    chargeKg: 100,
    scaled: 8.914592,
    kPa: 17.47073807926481,
  },
  {
    chargeKg: 100,
    scaled: 9.737601,
    kPa: 15.443443601628044,
  },
  {
    chargeKg: 100,
    scaled: 10.636592,
    kPa: 13.692779273577624,
  },
  {
    chargeKg: 100,
    scaled: 11.618578,
    kPa: 12.172771896964967,
  },
  {
    chargeKg: 100,
    scaled: 12.691223,
    kPa: 10.845899952350555,
  },
  {
    chargeKg: 100,
    scaled: 13.862897,
    kPa: 9.681434810626476,
  },
  {
    chargeKg: 100,
    scaled: 15.142741,
    kPa: 8.65413441649322,
  },
  {
    chargeKg: 100,
    scaled: 16.540742,
    kPa: 7.743210298952623,
  },
  {
    chargeKg: 100,
    scaled: 18.067809,
    kPa: 6.931507181495348,
  },
  {
    chargeKg: 100,
    scaled: 19.735857,
    kPa: 6.204848373748006,
  },
  {
    chargeKg: 100,
    scaled: 21.557902,
    kPa: 5.5515106742244225,
  },
  {
    chargeKg: 100,
    scaled: 23.548161,
    kPa: 4.961800551203858,
  },
  {
    chargeKg: 100,
    scaled: 25.722163,
    kPa: 4.4188225115288935,
  },
  {
    chargeKg: 100,
    scaled: 28.096873,
    kPa: 3.902678219361163,
  },
  {
    chargeKg: 100,
    scaled: 30.69082,
    kPa: 3.4468225967750477,
  },
  {
    chargeKg: 100,
    scaled: 33.524244,
    kPa: 3.0442135748470207,
  },
  {
    chargeKg: 100,
    scaled: 36.619254,
    kPa: 2.688631639456465,
  },
  {
    chargeKg: 100,
    scaled: 40.0,
    kPa: 2.3745837520777826,
  },
  {
    chargeKg: 1000,
    scaled: 0.2,
    kPa: 17310.35998012716,
  },
  {
    chargeKg: 1000,
    scaled: 0.218464,
    kPa: 15397.0000120463,
  },
  {
    chargeKg: 1000,
    scaled: 0.238633,
    kPa: 13720.545972797197,
  },
  {
    chargeKg: 1000,
    scaled: 0.260664,
    kPa: 12234.500181703123,
  },
  {
    chargeKg: 1000,
    scaled: 0.284729,
    kPa: 10904.313334952703,
  },
  {
    chargeKg: 1000,
    scaled: 0.311016,
    kPa: 9704.401958115983,
  },
  {
    chargeKg: 1000,
    scaled: 0.339729,
    kPa: 8615.929178570845,
  },
  {
    chargeKg: 1000,
    scaled: 0.371094,
    kPa: 7625.113165942521,
  },
  {
    chargeKg: 1000,
    scaled: 0.405354,
    kPa: 6721.90933246499,
  },
  {
    chargeKg: 1000,
    scaled: 0.442776,
    kPa: 5898.9669004255775,
  },
  {
    chargeKg: 1000,
    scaled: 0.483654,
    kPa: 5150.796639536418,
  },
  {
    chargeKg: 1000,
    scaled: 0.528306,
    kPa: 4473.110025053239,
  },
  {
    chargeKg: 1000,
    scaled: 0.57708,
    kPa: 3862.3044261384166,
  },
  {
    chargeKg: 1000,
    scaled: 0.630357,
    kPa: 3315.0767923078415,
  },
  {
    chargeKg: 1000,
    scaled: 0.688552,
    kPa: 2828.1516595160238,
  },
  {
    chargeKg: 1000,
    scaled: 0.752121,
    kPa: 2398.1097864251446,
  },
  {
    chargeKg: 1000,
    scaled: 0.821558,
    kPa: 2021.3027266722509,
  },
  {
    chargeKg: 1000,
    scaled: 0.897405,
    kPa: 1693.8372497003234,
  },
  {
    chargeKg: 1000,
    scaled: 0.980255,
    kPa: 1411.6125518903814,
  },
  {
    chargeKg: 1000,
    scaled: 1.070753,
    kPa: 1170.3931461092895,
  },
  {
    chargeKg: 1000,
    scaled: 1.169607,
    kPa: 965.9013674702634,
  },
  {
    chargeKg: 1000,
    scaled: 1.277587,
    kPa: 793.9155074145746,
  },
  {
    chargeKg: 1000,
    scaled: 1.395536,
    kPa: 650.3624179015258,
  },
  {
    chargeKg: 1000,
    scaled: 1.524374,
    kPa: 531.396642330283,
  },
  {
    chargeKg: 1000,
    scaled: 1.665106,
    kPa: 433.46134610877033,
  },
  {
    chargeKg: 1000,
    scaled: 1.818832,
    kPa: 353.329210453883,
  },
  {
    chargeKg: 1000,
    scaled: 1.986749,
    kPa: 288.1237912729341,
  },
  {
    chargeKg: 1000,
    scaled: 2.170169,
    kPa: 235.32351964287713,
  },
  {
    chargeKg: 1000,
    scaled: 2.370522,
    kPa: 192.75152700306094,
  },
  {
    chargeKg: 1000,
    scaled: 2.589372,
    kPa: 158.55489400866523,
  },
  {
    chargeKg: 1000,
    scaled: 2.828427,
    kPa: 131.17687416700196,
  },
  {
    chargeKg: 1000,
    scaled: 3.089552,
    kPa: 108.75345140657056,
  },
  {
    chargeKg: 1000,
    scaled: 3.374784,
    kPa: 90.61920068285787,
  },
  {
    chargeKg: 1000,
    scaled: 3.686349,
    kPa: 75.9723308682312,
  },
  {
    chargeKg: 1000,
    scaled: 4.026679,
    kPa: 64.07386606527938,
  },
  {
    chargeKg: 1000,
    scaled: 4.398428,
    kPa: 54.35266463928048,
  },
  {
    chargeKg: 1000,
    scaled: 4.804498,
    kPa: 46.36511412903269,
  },
  {
    chargeKg: 1000,
    scaled: 5.248056,
    kPa: 39.764957855049715,
  },
  {
    chargeKg: 1000,
    scaled: 5.732565,
    kPa: 34.28060744224936,
  },
  {
    chargeKg: 1000,
    scaled: 6.261804,
    kPa: 29.69800929554826,
  },
  {
    chargeKg: 1000,
    scaled: 6.839904,
    kPa: 25.84764884117841,
  },
  {
    chargeKg: 1000,
    scaled: 7.471374,
    kPa: 22.594650362540467,
  },
  {
    chargeKg: 1000,
    scaled: 8.161143,
    kPa: 19.831202468745733,
  },
  {
    chargeKg: 1000,
    scaled: 8.914592,
    kPa: 17.47073807926481,
  },
  {
    chargeKg: 1000,
    scaled: 9.737601,
    kPa: 15.443443601628044,
  },
  {
    chargeKg: 1000,
    scaled: 10.636592,
    kPa: 13.692779273577624,
  },
  {
    chargeKg: 1000,
    scaled: 11.618578,
    kPa: 12.172771896964967,
  },
  {
    chargeKg: 1000,
    scaled: 12.691223,
    kPa: 10.845899952350555,
  },
  {
    chargeKg: 1000,
    scaled: 13.862897,
    kPa: 9.681434810626476,
  },
  {
    chargeKg: 1000,
    scaled: 15.142741,
    kPa: 8.65413441649322,
  },
  {
    chargeKg: 1000,
    scaled: 16.540742,
    kPa: 7.743210298952623,
  },
  {
    chargeKg: 1000,
    scaled: 18.067809,
    kPa: 6.931507181495348,
  },
  {
    chargeKg: 1000,
    scaled: 19.735857,
    kPa: 6.204848373748006,
  },
  {
    chargeKg: 1000,
    scaled: 21.557902,
    kPa: 5.5515106742244225,
  },
  {
    chargeKg: 1000,
    scaled: 23.548161,
    kPa: 4.961800551203858,
  },
  {
    chargeKg: 1000,
    scaled: 25.722163,
    kPa: 4.4188225115288935,
  },
  {
    chargeKg: 1000,
    scaled: 28.096873,
    kPa: 3.902678219361163,
  },
  {
    chargeKg: 1000,
    scaled: 30.69082,
    kPa: 3.4468225967750477,
  },
  {
    chargeKg: 1000,
    scaled: 33.524244,
    kPa: 3.0442135748470207,
  },
  {
    chargeKg: 1000,
    scaled: 36.619254,
    kPa: 2.688631639456465,
  },
  {
    chargeKg: 1000,
    scaled: 40.0,
    kPa: 2.3745837520777826,
  },
  {
    chargeKg: 10000,
    scaled: 0.2,
    kPa: 17310.35998012716,
  },
  {
    chargeKg: 10000,
    scaled: 0.218464,
    kPa: 15397.0000120463,
  },
  {
    chargeKg: 10000,
    scaled: 0.238633,
    kPa: 13720.545972797197,
  },
  {
    chargeKg: 10000,
    scaled: 0.260664,
    kPa: 12234.500181703123,
  },
  {
    chargeKg: 10000,
    scaled: 0.284729,
    kPa: 10904.313334952703,
  },
  {
    chargeKg: 10000,
    scaled: 0.311016,
    kPa: 9704.401958115983,
  },
  {
    chargeKg: 10000,
    scaled: 0.339729,
    kPa: 8615.929178570845,
  },
  {
    chargeKg: 10000,
    scaled: 0.371094,
    kPa: 7625.113165942521,
  },
  {
    chargeKg: 10000,
    scaled: 0.405354,
    kPa: 6721.90933246499,
  },
  {
    chargeKg: 10000,
    scaled: 0.442776,
    kPa: 5898.9669004255775,
  },
  {
    chargeKg: 10000,
    scaled: 0.483654,
    kPa: 5150.796639536427,
  },
  {
    chargeKg: 10000,
    scaled: 0.528306,
    kPa: 4473.110025053239,
  },
  {
    chargeKg: 10000,
    scaled: 0.57708,
    kPa: 3862.3044261384166,
  },
  {
    chargeKg: 10000,
    scaled: 0.630357,
    kPa: 3315.0767923078415,
  },
  {
    chargeKg: 10000,
    scaled: 0.688552,
    kPa: 2828.1516595160238,
  },
  {
    chargeKg: 10000,
    scaled: 0.752121,
    kPa: 2398.1097864251446,
  },
  {
    chargeKg: 10000,
    scaled: 0.821558,
    kPa: 2021.3027266722509,
  },
  {
    chargeKg: 10000,
    scaled: 0.897405,
    kPa: 1693.8372497003234,
  },
  {
    chargeKg: 10000,
    scaled: 0.980255,
    kPa: 1411.6125518903814,
  },
  {
    chargeKg: 10000,
    scaled: 1.070753,
    kPa: 1170.3931461092895,
  },
  {
    chargeKg: 10000,
    scaled: 1.169607,
    kPa: 965.9013674702634,
  },
  {
    chargeKg: 10000,
    scaled: 1.277587,
    kPa: 793.9155074145746,
  },
  {
    chargeKg: 10000,
    scaled: 1.395536,
    kPa: 650.3624179015258,
  },
  {
    chargeKg: 10000,
    scaled: 1.524374,
    kPa: 531.3966423302835,
  },
  {
    chargeKg: 10000,
    scaled: 1.665106,
    kPa: 433.46134610877033,
  },
  {
    chargeKg: 10000,
    scaled: 1.818832,
    kPa: 353.329210453883,
  },
  {
    chargeKg: 10000,
    scaled: 1.986749,
    kPa: 288.1237912729341,
  },
  {
    chargeKg: 10000,
    scaled: 2.170169,
    kPa: 235.32351964287713,
  },
  {
    chargeKg: 10000,
    scaled: 2.370522,
    kPa: 192.75152700306094,
  },
  {
    chargeKg: 10000,
    scaled: 2.589372,
    kPa: 158.55489400866523,
  },
  {
    chargeKg: 10000,
    scaled: 2.828427,
    kPa: 131.17687416700196,
  },
  {
    chargeKg: 10000,
    scaled: 3.089552,
    kPa: 108.75345140657056,
  },
  {
    chargeKg: 10000,
    scaled: 3.374784,
    kPa: 90.61920068285787,
  },
  {
    chargeKg: 10000,
    scaled: 3.686349,
    kPa: 75.97233086823113,
  },
  {
    chargeKg: 10000,
    scaled: 4.026679,
    kPa: 64.07386606527938,
  },
  {
    chargeKg: 10000,
    scaled: 4.398428,
    kPa: 54.35266463928048,
  },
  {
    chargeKg: 10000,
    scaled: 4.804498,
    kPa: 46.36511412903269,
  },
  {
    chargeKg: 10000,
    scaled: 5.248056,
    kPa: 39.764957855049715,
  },
  {
    chargeKg: 10000,
    scaled: 5.732565,
    kPa: 34.28060744224936,
  },
  {
    chargeKg: 10000,
    scaled: 6.261804,
    kPa: 29.69800929554826,
  },
  {
    chargeKg: 10000,
    scaled: 6.839904,
    kPa: 25.84764884117839,
  },
  {
    chargeKg: 10000,
    scaled: 7.471374,
    kPa: 22.594650362540467,
  },
  {
    chargeKg: 10000,
    scaled: 8.161143,
    kPa: 19.831202468745733,
  },
  {
    chargeKg: 10000,
    scaled: 8.914592,
    kPa: 17.47073807926481,
  },
  {
    chargeKg: 10000,
    scaled: 9.737601,
    kPa: 15.443443601628044,
  },
  {
    chargeKg: 10000,
    scaled: 10.636592,
    kPa: 13.692779273577624,
  },
  {
    chargeKg: 10000,
    scaled: 11.618578,
    kPa: 12.172771896964967,
  },
  {
    chargeKg: 10000,
    scaled: 12.691223,
    kPa: 10.845899952350555,
  },
  {
    chargeKg: 10000,
    scaled: 13.862897,
    kPa: 9.681434810626468,
  },
  {
    chargeKg: 10000,
    scaled: 15.142741,
    kPa: 8.65413441649322,
  },
  {
    chargeKg: 10000,
    scaled: 16.540742,
    kPa: 7.743210298952623,
  },
  {
    chargeKg: 10000,
    scaled: 18.067809,
    kPa: 6.931507181495348,
  },
  {
    chargeKg: 10000,
    scaled: 19.735857,
    kPa: 6.204848373748006,
  },
  {
    chargeKg: 10000,
    scaled: 21.557902,
    kPa: 5.5515106742244225,
  },
  {
    chargeKg: 10000,
    scaled: 23.548161,
    kPa: 4.961800551203858,
  },
  {
    chargeKg: 10000,
    scaled: 25.722163,
    kPa: 4.4188225115288935,
  },
  {
    chargeKg: 10000,
    scaled: 28.096873,
    kPa: 3.9026782193611664,
  },
  {
    chargeKg: 10000,
    scaled: 30.69082,
    kPa: 3.4468225967750477,
  },
  {
    chargeKg: 10000,
    scaled: 33.524244,
    kPa: 3.0442135748470207,
  },
  {
    chargeKg: 10000,
    scaled: 36.619254,
    kPa: 2.688631639456465,
  },
  {
    chargeKg: 10000,
    scaled: 40.0,
    kPa: 2.3745837520777826,
  },
  {
    chargeKg: 100000,
    scaled: 0.2,
    kPa: 17310.35998012716,
  },
  {
    chargeKg: 100000,
    scaled: 0.218464,
    kPa: 15397.0000120463,
  },
  {
    chargeKg: 100000,
    scaled: 0.238633,
    kPa: 13720.545972797197,
  },
  {
    chargeKg: 100000,
    scaled: 0.260664,
    kPa: 12234.500181703123,
  },
  {
    chargeKg: 100000,
    scaled: 0.284729,
    kPa: 10904.313334952703,
  },
  {
    chargeKg: 100000,
    scaled: 0.311016,
    kPa: 9704.401958115983,
  },
  {
    chargeKg: 100000,
    scaled: 0.339729,
    kPa: 8615.929178570845,
  },
  {
    chargeKg: 100000,
    scaled: 0.371094,
    kPa: 7625.113165942521,
  },
  {
    chargeKg: 100000,
    scaled: 0.405354,
    kPa: 6721.90933246499,
  },
  {
    chargeKg: 100000,
    scaled: 0.442776,
    kPa: 5898.9669004255775,
  },
  {
    chargeKg: 100000,
    scaled: 0.483654,
    kPa: 5150.796639536427,
  },
  {
    chargeKg: 100000,
    scaled: 0.528306,
    kPa: 4473.110025053239,
  },
  {
    chargeKg: 100000,
    scaled: 0.57708,
    kPa: 3862.3044261384166,
  },
  {
    chargeKg: 100000,
    scaled: 0.630357,
    kPa: 3315.0767923078415,
  },
  {
    chargeKg: 100000,
    scaled: 0.688552,
    kPa: 2828.1516595160238,
  },
  {
    chargeKg: 100000,
    scaled: 0.752121,
    kPa: 2398.1097864251446,
  },
  {
    chargeKg: 100000,
    scaled: 0.821558,
    kPa: 2021.3027266722509,
  },
  {
    chargeKg: 100000,
    scaled: 0.897405,
    kPa: 1693.8372497003234,
  },
  {
    chargeKg: 100000,
    scaled: 0.980255,
    kPa: 1411.6125518903814,
  },
  {
    chargeKg: 100000,
    scaled: 1.070753,
    kPa: 1170.3931461092895,
  },
  {
    chargeKg: 100000,
    scaled: 1.169607,
    kPa: 965.9013674702634,
  },
  {
    chargeKg: 100000,
    scaled: 1.277587,
    kPa: 793.9155074145746,
  },
  {
    chargeKg: 100000,
    scaled: 1.395536,
    kPa: 650.3624179015258,
  },
  {
    chargeKg: 100000,
    scaled: 1.524374,
    kPa: 531.396642330283,
  },
  {
    chargeKg: 100000,
    scaled: 1.665106,
    kPa: 433.46134610877033,
  },
  {
    chargeKg: 100000,
    scaled: 1.818832,
    kPa: 353.329210453883,
  },
  {
    chargeKg: 100000,
    scaled: 1.986749,
    kPa: 288.1237912729341,
  },
  {
    chargeKg: 100000,
    scaled: 2.170169,
    kPa: 235.32351964287713,
  },
  {
    chargeKg: 100000,
    scaled: 2.370522,
    kPa: 192.75152700306094,
  },
  {
    chargeKg: 100000,
    scaled: 2.589372,
    kPa: 158.55489400866523,
  },
  {
    chargeKg: 100000,
    scaled: 2.828427,
    kPa: 131.17687416700196,
  },
  {
    chargeKg: 100000,
    scaled: 3.089552,
    kPa: 108.75345140657056,
  },
  {
    chargeKg: 100000,
    scaled: 3.374784,
    kPa: 90.61920068285787,
  },
  {
    chargeKg: 100000,
    scaled: 3.686349,
    kPa: 75.9723308682312,
  },
  {
    chargeKg: 100000,
    scaled: 4.026679,
    kPa: 64.07386606527938,
  },
  {
    chargeKg: 100000,
    scaled: 4.398428,
    kPa: 54.35266463928048,
  },
  {
    chargeKg: 100000,
    scaled: 4.804498,
    kPa: 46.36511412903269,
  },
  {
    chargeKg: 100000,
    scaled: 5.248056,
    kPa: 39.764957855049715,
  },
  {
    chargeKg: 100000,
    scaled: 5.732565,
    kPa: 34.28060744224936,
  },
  {
    chargeKg: 100000,
    scaled: 6.261804,
    kPa: 29.69800929554826,
  },
  {
    chargeKg: 100000,
    scaled: 6.839904,
    kPa: 25.84764884117839,
  },
  {
    chargeKg: 100000,
    scaled: 7.471374,
    kPa: 22.594650362540467,
  },
  {
    chargeKg: 100000,
    scaled: 8.161143,
    kPa: 19.831202468745733,
  },
  {
    chargeKg: 100000,
    scaled: 8.914592,
    kPa: 17.47073807926481,
  },
  {
    chargeKg: 100000,
    scaled: 9.737601,
    kPa: 15.443443601628044,
  },
  {
    chargeKg: 100000,
    scaled: 10.636592,
    kPa: 13.692779273577624,
  },
  {
    chargeKg: 100000,
    scaled: 11.618578,
    kPa: 12.172771896964967,
  },
  {
    chargeKg: 100000,
    scaled: 12.691223,
    kPa: 10.845899952350555,
  },
  {
    chargeKg: 100000,
    scaled: 13.862897,
    kPa: 9.681434810626476,
  },
  {
    chargeKg: 100000,
    scaled: 15.142741,
    kPa: 8.65413441649322,
  },
  {
    chargeKg: 100000,
    scaled: 16.540742,
    kPa: 7.743210298952623,
  },
  {
    chargeKg: 100000,
    scaled: 18.067809,
    kPa: 6.931507181495348,
  },
  {
    chargeKg: 100000,
    scaled: 19.735857,
    kPa: 6.204848373748006,
  },
  {
    chargeKg: 100000,
    scaled: 21.557902,
    kPa: 5.5515106742244225,
  },
  {
    chargeKg: 100000,
    scaled: 23.548161,
    kPa: 4.961800551203858,
  },
  {
    chargeKg: 100000,
    scaled: 25.722163,
    kPa: 4.4188225115288935,
  },
  {
    chargeKg: 100000,
    scaled: 28.096873,
    kPa: 3.902678219361163,
  },
  {
    chargeKg: 100000,
    scaled: 30.69082,
    kPa: 3.4468225967750445,
  },
  {
    chargeKg: 100000,
    scaled: 33.524244,
    kPa: 3.0442135748470207,
  },
  {
    chargeKg: 100000,
    scaled: 36.619254,
    kPa: 2.688631639456465,
  },
  {
    chargeKg: 100000,
    scaled: 40.0,
    kPa: 2.3745837520777826,
  },
  {
    chargeKg: 1000000,
    scaled: 0.2,
    kPa: 17310.35998012716,
  },
  {
    chargeKg: 1000000,
    scaled: 0.218464,
    kPa: 15397.0000120463,
  },
  {
    chargeKg: 1000000,
    scaled: 0.238633,
    kPa: 13720.545972797197,
  },
  {
    chargeKg: 1000000,
    scaled: 0.260664,
    kPa: 12234.500181703123,
  },
  {
    chargeKg: 1000000,
    scaled: 0.284729,
    kPa: 10904.313334952703,
  },
  {
    chargeKg: 1000000,
    scaled: 0.311016,
    kPa: 9704.401958115983,
  },
  {
    chargeKg: 1000000,
    scaled: 0.339729,
    kPa: 8615.929178570845,
  },
  {
    chargeKg: 1000000,
    scaled: 0.371094,
    kPa: 7625.113165942521,
  },
  {
    chargeKg: 1000000,
    scaled: 0.405354,
    kPa: 6721.90933246499,
  },
  {
    chargeKg: 1000000,
    scaled: 0.442776,
    kPa: 5898.9669004255775,
  },
  {
    chargeKg: 1000000,
    scaled: 0.483654,
    kPa: 5150.796639536427,
  },
  {
    chargeKg: 1000000,
    scaled: 0.528306,
    kPa: 4473.110025053239,
  },
  {
    chargeKg: 1000000,
    scaled: 0.57708,
    kPa: 3862.3044261384166,
  },
  {
    chargeKg: 1000000,
    scaled: 0.630357,
    kPa: 3315.0767923078415,
  },
  {
    chargeKg: 1000000,
    scaled: 0.688552,
    kPa: 2828.1516595160238,
  },
  {
    chargeKg: 1000000,
    scaled: 0.752121,
    kPa: 2398.1097864251446,
  },
  {
    chargeKg: 1000000,
    scaled: 0.821558,
    kPa: 2021.3027266722509,
  },
  {
    chargeKg: 1000000,
    scaled: 0.897405,
    kPa: 1693.8372497003234,
  },
  {
    chargeKg: 1000000,
    scaled: 0.980255,
    kPa: 1411.6125518903814,
  },
  {
    chargeKg: 1000000,
    scaled: 1.070753,
    kPa: 1170.3931461092895,
  },
  {
    chargeKg: 1000000,
    scaled: 1.169607,
    kPa: 965.9013674702634,
  },
  {
    chargeKg: 1000000,
    scaled: 1.277587,
    kPa: 793.9155074145746,
  },
  {
    chargeKg: 1000000,
    scaled: 1.395536,
    kPa: 650.3624179015258,
  },
  {
    chargeKg: 1000000,
    scaled: 1.524374,
    kPa: 531.396642330283,
  },
  {
    chargeKg: 1000000,
    scaled: 1.665106,
    kPa: 433.46134610877033,
  },
  {
    chargeKg: 1000000,
    scaled: 1.818832,
    kPa: 353.329210453883,
  },
  {
    chargeKg: 1000000,
    scaled: 1.986749,
    kPa: 288.1237912729341,
  },
  {
    chargeKg: 1000000,
    scaled: 2.170169,
    kPa: 235.32351964287713,
  },
  {
    chargeKg: 1000000,
    scaled: 2.370522,
    kPa: 192.75152700306094,
  },
  {
    chargeKg: 1000000,
    scaled: 2.589372,
    kPa: 158.55489400866523,
  },
  {
    chargeKg: 1000000,
    scaled: 2.828427,
    kPa: 131.17687416700196,
  },
  {
    chargeKg: 1000000,
    scaled: 3.089552,
    kPa: 108.75345140657066,
  },
  {
    chargeKg: 1000000,
    scaled: 3.374784,
    kPa: 90.61920068285787,
  },
  {
    chargeKg: 1000000,
    scaled: 3.686349,
    kPa: 75.97233086823113,
  },
  {
    chargeKg: 1000000,
    scaled: 4.026679,
    kPa: 64.07386606527938,
  },
  {
    chargeKg: 1000000,
    scaled: 4.398428,
    kPa: 54.35266463928048,
  },
  {
    chargeKg: 1000000,
    scaled: 4.804498,
    kPa: 46.36511412903269,
  },
  {
    chargeKg: 1000000,
    scaled: 5.248056,
    kPa: 39.76495785504966,
  },
  {
    chargeKg: 1000000,
    scaled: 5.732565,
    kPa: 34.28060744224936,
  },
  {
    chargeKg: 1000000,
    scaled: 6.261804,
    kPa: 29.69800929554826,
  },
  {
    chargeKg: 1000000,
    scaled: 6.839904,
    kPa: 25.84764884117839,
  },
  {
    chargeKg: 1000000,
    scaled: 7.471374,
    kPa: 22.594650362540467,
  },
  {
    chargeKg: 1000000,
    scaled: 8.161143,
    kPa: 19.831202468745733,
  },
  {
    chargeKg: 1000000,
    scaled: 8.914592,
    kPa: 17.47073807926481,
  },
  {
    chargeKg: 1000000,
    scaled: 9.737601,
    kPa: 15.443443601628044,
  },
  {
    chargeKg: 1000000,
    scaled: 10.636592,
    kPa: 13.692779273577624,
  },
  {
    chargeKg: 1000000,
    scaled: 11.618578,
    kPa: 12.172771896964967,
  },
  {
    chargeKg: 1000000,
    scaled: 12.691223,
    kPa: 10.845899952350555,
  },
  {
    chargeKg: 1000000,
    scaled: 13.862897,
    kPa: 9.681434810626476,
  },
  {
    chargeKg: 1000000,
    scaled: 15.142741,
    kPa: 8.65413441649322,
  },
  {
    chargeKg: 1000000,
    scaled: 16.540742,
    kPa: 7.743210298952623,
  },
  {
    chargeKg: 1000000,
    scaled: 18.067809,
    kPa: 6.931507181495348,
  },
  {
    chargeKg: 1000000,
    scaled: 19.735857,
    kPa: 6.204848373748006,
  },
  {
    chargeKg: 1000000,
    scaled: 21.557902,
    kPa: 5.5515106742244225,
  },
  {
    chargeKg: 1000000,
    scaled: 23.548161,
    kPa: 4.961800551203858,
  },
  {
    chargeKg: 1000000,
    scaled: 25.722163,
    kPa: 4.4188225115288935,
  },
  {
    chargeKg: 1000000,
    scaled: 28.096873,
    kPa: 3.902678219361163,
  },
  {
    chargeKg: 1000000,
    scaled: 30.69082,
    kPa: 3.4468225967750477,
  },
  {
    chargeKg: 1000000,
    scaled: 33.524244,
    kPa: 3.0442135748470207,
  },
  {
    chargeKg: 1000000,
    scaled: 36.619254,
    kPa: 2.688631639456465,
  },
  {
    chargeKg: 1000000,
    scaled: 40.0,
    kPa: 2.3745837520777826,
  },
  {
    chargeKg: 1000000000,
    scaled: 0.2,
    kPa: 17310.35998012716,
  },
  {
    chargeKg: 1000000000,
    scaled: 0.218464,
    kPa: 15397.0000120463,
  },
  {
    chargeKg: 1000000000,
    scaled: 0.238633,
    kPa: 13720.545972797197,
  },
  {
    chargeKg: 1000000000,
    scaled: 0.260664,
    kPa: 12234.500181703123,
  },
  {
    chargeKg: 1000000000,
    scaled: 0.284729,
    kPa: 10904.313334952703,
  },
  {
    chargeKg: 1000000000,
    scaled: 0.311016,
    kPa: 9704.401958115983,
  },
  {
    chargeKg: 1000000000,
    scaled: 0.339729,
    kPa: 8615.929178570845,
  },
  {
    chargeKg: 1000000000,
    scaled: 0.371094,
    kPa: 7625.113165942521,
  },
  {
    chargeKg: 1000000000,
    scaled: 0.405354,
    kPa: 6721.90933246499,
  },
  {
    chargeKg: 1000000000,
    scaled: 0.442776,
    kPa: 5898.9669004255775,
  },
  {
    chargeKg: 1000000000,
    scaled: 0.483654,
    kPa: 5150.796639536427,
  },
  {
    chargeKg: 1000000000,
    scaled: 0.528306,
    kPa: 4473.110025053239,
  },
  {
    chargeKg: 1000000000,
    scaled: 0.57708,
    kPa: 3862.3044261384166,
  },
  {
    chargeKg: 1000000000,
    scaled: 0.630357,
    kPa: 3315.0767923078415,
  },
  {
    chargeKg: 1000000000,
    scaled: 0.688552,
    kPa: 2828.1516595160238,
  },
  {
    chargeKg: 1000000000,
    scaled: 0.752121,
    kPa: 2398.1097864251446,
  },
  {
    chargeKg: 1000000000,
    scaled: 0.821558,
    kPa: 2021.3027266722509,
  },
  {
    chargeKg: 1000000000,
    scaled: 0.897405,
    kPa: 1693.8372497003234,
  },
  {
    chargeKg: 1000000000,
    scaled: 0.980255,
    kPa: 1411.6125518903814,
  },
  {
    chargeKg: 1000000000,
    scaled: 1.070753,
    kPa: 1170.3931461092895,
  },
  {
    chargeKg: 1000000000,
    scaled: 1.169607,
    kPa: 965.9013674702634,
  },
  {
    chargeKg: 1000000000,
    scaled: 1.277587,
    kPa: 793.9155074145746,
  },
  {
    chargeKg: 1000000000,
    scaled: 1.395536,
    kPa: 650.3624179015258,
  },
  {
    chargeKg: 1000000000,
    scaled: 1.524374,
    kPa: 531.396642330283,
  },
  {
    chargeKg: 1000000000,
    scaled: 1.665106,
    kPa: 433.46134610877033,
  },
  {
    chargeKg: 1000000000,
    scaled: 1.818832,
    kPa: 353.329210453883,
  },
  {
    chargeKg: 1000000000,
    scaled: 1.986749,
    kPa: 288.1237912729341,
  },
  {
    chargeKg: 1000000000,
    scaled: 2.170169,
    kPa: 235.32351964287713,
  },
  {
    chargeKg: 1000000000,
    scaled: 2.370522,
    kPa: 192.75152700306094,
  },
  {
    chargeKg: 1000000000,
    scaled: 2.589372,
    kPa: 158.55489400866523,
  },
  {
    chargeKg: 1000000000,
    scaled: 2.828427,
    kPa: 131.17687416700196,
  },
  {
    chargeKg: 1000000000,
    scaled: 3.089552,
    kPa: 108.75345140657056,
  },
  {
    chargeKg: 1000000000,
    scaled: 3.374784,
    kPa: 90.61920068285787,
  },
  {
    chargeKg: 1000000000,
    scaled: 3.686349,
    kPa: 75.97233086823113,
  },
  {
    chargeKg: 1000000000,
    scaled: 4.026679,
    kPa: 64.07386606527938,
  },
  {
    chargeKg: 1000000000,
    scaled: 4.398428,
    kPa: 54.35266463928048,
  },
  {
    chargeKg: 1000000000,
    scaled: 4.804498,
    kPa: 46.36511412903269,
  },
  {
    chargeKg: 1000000000,
    scaled: 5.248056,
    kPa: 39.764957855049715,
  },
  {
    chargeKg: 1000000000,
    scaled: 5.732565,
    kPa: 34.28060744224936,
  },
  {
    chargeKg: 1000000000,
    scaled: 6.261804,
    kPa: 29.69800929554826,
  },
  {
    chargeKg: 1000000000,
    scaled: 6.839904,
    kPa: 25.84764884117839,
  },
  {
    chargeKg: 1000000000,
    scaled: 7.471374,
    kPa: 22.594650362540467,
  },
  {
    chargeKg: 1000000000,
    scaled: 8.161143,
    kPa: 19.831202468745733,
  },
  {
    chargeKg: 1000000000,
    scaled: 8.914592,
    kPa: 17.47073807926481,
  },
  {
    chargeKg: 1000000000,
    scaled: 9.737601,
    kPa: 15.443443601628044,
  },
  {
    chargeKg: 1000000000,
    scaled: 10.636592,
    kPa: 13.692779273577624,
  },
  {
    chargeKg: 1000000000,
    scaled: 11.618578,
    kPa: 12.172771896964967,
  },
  {
    chargeKg: 1000000000,
    scaled: 12.691223,
    kPa: 10.845899952350555,
  },
  {
    chargeKg: 1000000000,
    scaled: 13.862897,
    kPa: 9.681434810626476,
  },
  {
    chargeKg: 1000000000,
    scaled: 15.142741,
    kPa: 8.65413441649322,
  },
  {
    chargeKg: 1000000000,
    scaled: 16.540742,
    kPa: 7.743210298952623,
  },
  {
    chargeKg: 1000000000,
    scaled: 18.067809,
    kPa: 6.931507181495348,
  },
  {
    chargeKg: 1000000000,
    scaled: 19.735857,
    kPa: 6.204848373748006,
  },
  {
    chargeKg: 1000000000,
    scaled: 21.557902,
    kPa: 5.5515106742244225,
  },
  {
    chargeKg: 1000000000,
    scaled: 23.548161,
    kPa: 4.961800551203858,
  },
  {
    chargeKg: 1000000000,
    scaled: 25.722163,
    kPa: 4.4188225115288935,
  },
  {
    chargeKg: 1000000000,
    scaled: 28.096873,
    kPa: 3.902678219361163,
  },
  {
    chargeKg: 1000000000,
    scaled: 30.69082,
    kPa: 3.4468225967750477,
  },
  {
    chargeKg: 1000000000,
    scaled: 33.524244,
    kPa: 3.0442135748470207,
  },
  {
    chargeKg: 1000000000,
    scaled: 36.619254,
    kPa: 2.688631639456465,
  },
  {
    chargeKg: 1000000000,
    scaled: 40.0,
    kPa: 2.3745837520777826,
  },
];

/** The package against IATG 01.80 (2021) Table 5, as a fraction. */
export const KINGERY_BULMASH_IATG_CHECK: readonly {
  readonly chargeKg: number;
  readonly rangeM: number;
  readonly iatgKpa: number;
  readonly packageKpa: number;
  readonly relative: number;
}[] = [
  {
    chargeKg: 1000,
    rangeM: 50,
    iatgKpa: 43.0,
    packageKpa: 43.22996372863541,
    relative: 0.005347993689195585,
  },
  {
    chargeKg: 10000,
    rangeM: 50,
    iatgKpa: 202.0,
    packageKpa: 202.1436147518722,
    relative: 0.0007109641181792803,
  },
  {
    chargeKg: 100000,
    rangeM: 50,
    iatgKpa: 1150.0,
    packageKpa: 1155.3376102195023,
    relative: 0.0046414001908714475,
  },
];
