import { SEAWATER_DENSITY, STANDARD_GRAVITY } from '../../constants.js';
import type { Meters } from '../../units.js';
import { m } from '../../units.js';
import { dispersionFactor } from '../../tsunami/dispersion.js';

/**
 * Extended tsunami estimators beyond the Ward & Asphaug impact source:
 *   - Synolakis 1987 sloping-beach run-up,
 *   - a Watts 2000-inspired submarine-landslide source amplitude,
 *   - a heuristic frequency-dispersion far-field amplitude envelope
 *     (Kajiura 1963 theory / Watada et al. 2014 trans-oceanic data).
 *
 * All fits carry ≥ ±factor-2 scatter on real data; use for
 * order-of-magnitude presentation only.
 */

/**
 * Run-up height of a long-wave tsunami on a plane-slope beach.
 *
 * Canonical Synolakis (1987) non-breaking run-up law:
 *
 *     R / d = 2.831 · √(cot β) · (H / d)^(5/4)
 *
 * The implementation below writes it in the algebraically-IDENTICAL
 * pivot form (prefactor H, exponent ¼ on H/d):
 *
 *     R_max = 2.831 · H · √(cot β) · (H / d)^(1/4)
 *
 * because  H · (H/d)^(1/4) = d · (H/d)^(5/4) = H^(5/4) · d^(−1/4).
 * (The ¼ here is NOT the canonical exponent — the full H-dependence is
 * 5/4 once the leading H is folded in. Do not "simplify" by dropping
 * the leading H.) where H is the incident deep-ocean wave amplitude,
 * β the beach slope angle, and d the offshore water depth at which H
 * is measured. Valid for NON-BREAKING waves; the caller caps run-up at
 * ~4× the incident amplitude (McCowan 1894 breaking limit).
 *
 * Reference: Synolakis, C. E. (1987). "The runup of solitary waves."
 * Journal of Fluid Mechanics 185: 523–545.
 * DOI: 10.1017/S002211208700329X.
 */
export function synolakisRunup(
  incidentAmplitude: Meters,
  beachSlopeRad: number,
  offshoreDepth: Meters
): Meters {
  const H = incidentAmplitude as number;
  const d = offshoreDepth as number;
  if (!Number.isFinite(H) || H <= 0 || !Number.isFinite(d) || d <= 0) return m(0);
  if (!Number.isFinite(beachSlopeRad) || beachSlopeRad <= 0) return m(0);
  const cotBeta = 1 / Math.tan(beachSlopeRad);
  return m(2.831 * H * Math.sqrt(cotBeta) * Math.pow(H / d, 0.25));
}

/**
 * Characteristic initial-wave amplitude generated by a submarine
 * landslide (solid-block approximation) from:
 *
 *   Watts, P. (2000). "Tsunami features of solid block underwater
 *    landslides." Journal of Waterway, Port, Coastal, and Ocean
 *    Engineering 126 (3): 144–152.
 *    DOI: 10.1061/(ASCE)0733-950X(2000)126:3(144).
 *
 * Watts (2000)-INSPIRED simplified form (NOT Watts' published
 * equation):
 *
 *     A₀ ≈ 0.1 · V^(1/3) · sin(θ)
 *
 * with V the slide bulk volume (m³) and θ the slope angle. Watts' full
 * characteristic amplitude additionally depends on slide thickness, the
 * submerged density contrast (ρ_slide/ρ_water − 1) and the slide Froude
 * number — none of which appear here; they are absorbed into the 0.1
 * prefactor. So this is a calibrated envelope, not a transcription of
 * Watts: it reproduces the Aitape-PNG 1998 slide (V ≈ 4 × 10⁶ m³,
 * θ ≈ 10°) within a factor of 2 against the observed 10–15 m local
 * runup. Order-of-magnitude only.
 */
export function submarineLandslideAmplitude(slideVolumeM3: number, slopeRad: number): Meters {
  if (!Number.isFinite(slideVolumeM3) || slideVolumeM3 <= 0) return m(0);
  if (!Number.isFinite(slopeRad) || slopeRad <= 0) return m(0);
  const A0 = 0.1 * Math.pow(slideVolumeM3, 1 / 3) * Math.sin(slopeRad);
  return m(A0);
}

/** Reference value: the peak open-ocean amplitude that the Ward &
 *  Asphaug 1/r formula would predict for the 2011 Tōhoku tsunami at
 *  DART buoy 21413 (1 500 km offshore).
 *
 *  A cross-check and nothing else — no product path reads it. It is
 *  an independent published formula fed an independent published
 *  source amplitude, which is what makes it worth keeping: the
 *  simulator's own chain is now one law end to end, and a law with
 *  nothing to disagree with is a law nobody is checking. */
export function tohoku2011DARTReference(): Meters {
  // Source amplitude from Satake et al. 2013 inversion: A0 ≈ 2 m at
  // the rupture edge (≈100 km from source), propagated at 1/r.
  const sourceAmplitude = 2; // m
  const sourceRange = 100_000; // m
  const dartRange = 1_500_000; // m (DART 21413)
  const geom = (sourceAmplitude * sourceRange) / dartRange;
  // Dispersion on this event's own wavelength and depth rather than a
  // fixed scale length. Twice the down-dip width — 205 km from the
  // Strasser regression, so 410 km — because that is the wavelength
  // the recorded period says a megathrust radiates on, and it is the
  // one the rest of the simulator uses. Over 4 km of ocean such a
  // wave keeps its shape for fifteen hundred kilometres, so this is
  // very nearly the bare 1/r figure either way; the point is that
  // there is no second answer to the question anywhere.
  void SEAWATER_DENSITY;
  void STANDARD_GRAVITY;
  return m(geom * dispersionFactor({ rangeM: dartRange, depthM: 4000, wavelengthM: 2 * 205_000 }));
}
